"""JavaScript / TypeScript stubs for call resolution.

Contains stub definitions for JavaScript/TypeScript built-in types,
DOM APIs, and Node.js globals.
"""

from __future__ import annotations

_JAVASCRIPT_STUBS: dict[str, list[str]] = {
    "Array": [
        "push", "pop", "shift", "unshift", "splice", "slice", "concat",
        "join", "toString", "indexOf", "lastIndexOf", "includes",
        "forEach", "map", "filter", "reduce", "reduceRight", "some",
        "every", "find", "findIndex", "flat", "flatMap", "fill",
        "sort", "reverse", "copyWithin", "entries", "keys", "values",
        "at", "findLast", "findLastIndex", "toReversed", "toSorted",
        "toSpliced", "with",
    ],
    "Object": [
        "keys", "values", "entries", "assign", "create", "defineProperty",
        "defineProperties", "getOwnPropertyDescriptor", "getOwnPropertyDescriptors",
        "getOwnPropertyNames", "getOwnPropertySymbols", "getPrototypeOf",
        "setPrototypeOf", "is", "isExtensible", "preventExtensions",
        "seal", "isSealed", "freeze", "isFrozen", "hasOwn", "has",
    ],
    "Map": [
        "get", "set", "has", "delete", "clear", "size", "entries",
        "keys", "values", "forEach",
    ],
    "Set": [
        "add", "delete", "has", "clear", "size", "entries", "keys",
        "values", "forEach", "intersection", "union", "difference",
        "symmetricDifference", "isSubsetOf", "isSupersetOf", "isDisjointFrom",
    ],
    "Promise": [
        "then", "catch", "finally", "all", "allSettled", "any", "race",
        "resolve", "reject",
    ],
    "Date": [
        "now", "parse", "UTC", "getFullYear", "getMonth", "getDate",
        "getDay", "getHours", "getMinutes", "getSeconds", "getTime",
        "setFullYear", "setMonth", "setDate", "setHours", "setMinutes",
        "setSeconds", "setTime", "toDateString", "toTimeString",
        "toISOString", "toJSON", "toString", "valueOf",
    ],
    "Error": [
        "name", "message", "stack", "cause",
    ],
    "console": [
        "log", "info", "warn", "error", "debug", "trace", "table",
        "count", "countReset", "time", "timeEnd", "timeLog",
        "assert", "dir", "dirxml", "group", "groupEnd", "clear",
    ],
    "process": [
        "exit", "version", "versions", "platform", "arch", "pid",
        "cwd", "chdir", "env", "argv", "stdin", "stdout", "stderr",
        "exitCode", "on", "emit", "hrtime",
        "memoryUsage", "cpuUsage", "umask",
    ],
    "String": [
        "charAt", "charCodeAt", "concat", "includes", "endsWith", "indexOf",
        "lastIndexOf", "localeCompare", "match", "matchAll", "normalize",
        "padEnd", "padStart", "repeat", "replace", "replaceAll", "search",
        "slice", "split", "startsWith", "substring", "toLocaleLowerCase",
        "toLocaleUpperCase", "toLowerCase", "toString", "toUpperCase",
        "trim", "trimStart", "trimEnd", "trimLeft", "trimRight",
        "valueOf", "at", "codePointAt", "fromCodePoint",
    ],
    "Number": [
        "isFinite", "isInteger", "isNaN", "isSafeInteger", "parseFloat",
        "parseInt", "toExponential", "toFixed", "toPrecision", "toString",
        "valueOf",
    ],
    "Math": [
        "abs", "acos", "acosh", "asin", "asinh", "atan", "atanh",
        "atan2", "cbrt", "ceil", "clz32", "cos", "cosh", "exp",
        "expm1", "floor", "fround", "hypot", "imul", "log", "log1p",
        "log10", "log2", "max", "min", "pow", "random", "round",
        "sign", "sin", "sinh", "sqrt", "tan", "tanh", "trunc",
    ],
    "RegExp": [
        "test", "exec", "source", "global", "ignoreCase", "multiline",
        "sticky", "unicode", "dotAll", "flags", "lastIndex",
    ],
    "JSON": ["parse", "stringify"],
    "ArrayBuffer": ["byteLength", "slice", "resize", "detach", "isView",
                    "byteLength", "maxByteLength", "transfer"],
    "Uint8Array": [
        "set", "subarray", "slice", "fill", "find", "findIndex", "forEach",
        "join", "lastIndexOf", "reverse", "sort", "toString",
    ],
    "Uint8ClampedArray": ["set", "subarray", "slice", "fill"],
    "Int8Array": ["set", "subarray", "slice", "fill"],
    "Int16Array": ["set", "subarray", "slice", "fill"],
    "Int32Array": ["set", "subarray", "slice", "fill"],
    "Uint16Array": ["set", "subarray", "slice", "fill"],
    "Uint32Array": ["set", "subarray", "slice", "fill"],
    "Float32Array": ["set", "subarray", "slice", "fill"],
    "Float64Array": ["set", "subarray", "slice", "fill"],
    "URL": [
        "parse", "resolve", "toString", "toJSON", "href", "protocol",
        "username", "password", "hostname", "host", "port", "pathname",
        "search", "hash", "searchParams", "origin",
    ],
    "URLSearchParams": [
        "append", "delete", "get", "getAll", "has", "set", "sort",
        "toString", "entries", "keys", "values", "forEach",
    ],
    "fetch": ["get", "post", "put", "delete", "patch"],
    "setTimeout": [],
    "setInterval": [],
    "require": ["resolve", "cache", "extensions"],

    # ── Popular JS/TS libraries ───────────────────────────────────────

    # ── lodash - utility library
    "_": [
        "get", "set", "merge", "cloneDeep", "isEqual", "isArray", "isObject",
        "isString", "isNumber", "isBoolean", "isNull", "isUndefined",
        "isFunction", "isPlainObject", "isNil", "isEmpty", "isFinite",
        "isInteger", "isSafeInteger", "isDate", "isRegExp", "isError",
        "map", "filter", "reduce", "find", "findLast", "findIndex",
        "findLastIndex", "groupBy", "keyBy", "sortBy", "orderBy",
        "uniq", "uniqBy", "uniqWith", "union", "intersection", "difference",
        "xor", "compact", "flatten", "flattenDeep", "flattenDepth",
        "drop", "dropRight", "dropWhile", "dropRightWhile",
        "take", "takeRight", "takeWhile", "takeRightWhile",
        "chunk", "zip", "unzip", "zipWith", "zipObject", "zipObjectDeep",
        "partition", "reject", "reject", "mapKeys", "mapValues",
        "pick", "omit", "pickBy", "omitBy", "transform",
        "castArray", "times", "iteratee", "attempt", "over", "overArgs",
        "overEvery", "overSome", "cond", "flip", "nthArg",
        "before", "after", "ary", "curry", "curryRight", "partial",
        "partialRight", "rearg", "rest", "spread", "flip",
        "memoize", "negate", "once", "overArgs", "method", "methodOf",
        "property", "propertyOf", "matches", "matchesProperty",
        "identity", "stubTrue", "stubFalse", "now", "uniqueId",
        "camelCase", "capitalize", "deburr", "endsWidth", "escape",
        "escapeRegExp", "kebabCase", "lowerCase", "lowerFirst",
        "pad", "padEnd", "padStart", "parseInt", "repeat", "replace",
        "snakeCase", "split", "startCase", "startsWith", "template",
        "templateSettings", "toFinite", "toInteger", "toLength",
        "toNumber", "toPlainObject", "toString", "trim", "trimEnd",
        "trimStart", "truncate", "unescape", "upperCase", "upperFirst",
        "words", "throttle", "debounce", "uniqueId",
    ],
    "lodash": [
        "get", "set", "merge", "cloneDeep", "isEqual", "isArray", "isObject",
        "isString", "isNumber", "isBoolean", "isNull", "isUndefined",
        "isFunction", "isPlainObject", "isNil", "isEmpty", "isFinite",
        "map", "filter", "reduce", "find", "groupBy", "sortBy",
        "uniq", "flatten", "chunk", "zip", "partition", "pick", "omit",
        "compact", "camelCase", "debounce", "throttle", "uniqueId",
    ],
    # ── axios - HTTP client
    "axios": [
        "get", "post", "put", "patch", "delete", "head", "options",
        "request", "create", "Cancel", "CancelToken", "isCancel",
        "all", "spread", "isAxiosError", "AxiosError", "AxiosResponse",
        "AxiosRequestConfig", "AxiosHeaders", "AxiosProxyConfig",
        "AxiosAdapter", "AxiosTransport", "FormData", "Blob",
        "ProgressEvent", "HttpHeaders", "HttpHeaderSource",
        "Method", "ResponseType", "Adapter", "AdapterReturnType",
        "AxiosInstance", "AxiosStatic", "AxiosPromise",
        "interceptors", "requests", "responses", "defaults",
        "cancelToken", "onUploadProgress", "onDownloadProgress",
        "maxContentLength", "maxBodyLength", "env", "agents",
        "formToJSON", "toFormData", "AxiosHeaders", "flattenHeaders",
    ],
    "Axios": [
        "get", "post", "put", "patch", "delete", "head", "options",
        "request", "getUri", "delete", "get", "head", "options",
        "post", "put", "patch", "interceptors", "defaults",
        "request", "getUri", "delete", "get", "head", "options",
        "post", "put", "patch", "interceptors", "defaults",
    ],
    "AxiosResponse": [
        "data", "status", "statusText", "headers", "config", "request",
        "toJSON", "isAxiosError", "toString", "is_cancelled",
    ],
    # ── express - web framework
    "express": [
        "app", "Application", "Request", "Response", "Router", "middleware",
        "static", "json", "urlencoded", "text", "raw", "vgful", "query",
        "use", "listen", "listenAsync", "mountpath", "path", "engine",
        "enable", "disable", "enabled", "disabled", "set", "get", "del",
        "all", "get", "head", "put", "post", "patch", "delete", "options",
        "trace", "copy", "lock", "mkcol", "move", "purge", "propfind",
        "proppatch", "unlock", "report", "mkactivity", "checkout",
        "merge", "msearch", "notify", "subscribe", "unsubscribe",
        "path", "route", "use", "engine", "listen", "settings",
        "locals", "name", "subpath", "unmount",
    ],
    "Express": [
        "app", "Application", "Request", "Response", "Router", "middleware",
        "use", "listen", "engine", "set", "get", "del", "all",
        "get", "head", "put", "post", "patch", "delete", "options",
        "route", "use", "engine", "listen", "settings", "locals",
        "name", "subpath", "unmount",
    ],
    "Request": [
        "app", "body", "cookies", "fresh", "hostname", "ip", "ips",
        "protocol", "secure", "xhr", "path", "originalUrl", "url",
        "baseUrl", "route", "params", "query", "res", "session",
        "stash", "subdomains", "is", "get", "header", "headers",
        "accepts", "acceptsLanguages", "acceptsCharsets", "acceptsEncodings",
        "attachment", "clearCookie", "download", "format", "redirect",
        "render", "send", "sendFile", "sendfile", "type", "vary",
        "app", "baseUrl", "body", "cookies", "fresh", "hostname", "ip",
        "ips", "method", "originalUrl", "params", "path", "protocol",
        "query", "res", "secure", "signedCookies", "stale", "xhr",
        "subdomains", "accepts", "acceptsCharsets", "acceptsEncodings",
        "acceptsLanguages", "get", "header", "headers", "is", "param",
        "range", "search", "store", "session",
    ],
    "Response": [
        "app", "headers", "sent", "statusCode", "statusMessage",
        "get", "set", "append", "clearCookie", "download",
        "end", "format", "json", "jsonp", "links", "location",
        "redirect", "render", "send", "sendFile", "sendfile", "type",
        "vary", "app", "headers", "sent", "statusCode", "statusMessage",
        "get", "set", "append", "clearCookie", "download", "end",
        "format", "json", "jsonp", "links", "location", "redirect",
        "render", "send", "sendFile", "sendfile", "type", "vary",
    ],
    # ── rxjs - reactive extensions
    "Observable": [
        "subscribe", "pipe", "forEach", "toPromise", "toAsync", "lastValueFrom",
        "firstValueFrom", "map", "filter", "reduce", "concatMap", "mergeMap",
        "switchMap", "flatMap", "exhaustMap", "concatAll", "mergeAll", "switchAll",
        "flatMapConcat", "flatMapMerge", "flatMapSwitch", "exhaust", "exhaustAll",
        "publish", "publishLast", "publishBehavior", "publishReplay",
        "share", "shareReplay", "multicast", "refCount", "connect",
        "retry", "retryWhen", "catchError", "catchError", "finalize",
        "tap", "do", "observeOn", "subscribeOn", "delay", "debounceTime",
        "throttleTime", "sampleTime", "timeout", "timeoutWith", "timeoutUntil",
        "window", "windowTime", "windowCount", "windowToggle", "windowWhen",
        "buffer", "bufferTime", "bufferCount", "bufferToggle", "bufferWhen",
        "elementAt", "single", "isEmpty", "count", "min", "max",
        "contains", "includes", "endsWith", "startsWith", "every", "some",
        "find", "findIndex", "toArray", "values", "keys", "entries",
    ],
    "Subject": [
        "next", "error", "complete", "hasError", "isStopped", "observers",
        "asObservable", "lift", "subscribe", "pipe", "getValue",
        "asObservable", "next", "error", "complete", "hasError",
        "isStopped", "observers", "asObservable", "lift", "subscribe",
    ],
    "BehaviorSubject": [
        "next", "error", "complete", "getValue", "value", "asObservable",
        "asObservable", "next", "error", "complete", "getValue", "value",
    ],
    "ReplaySubject": [
        "next", "error", "complete", "asObservable", "asObservable",
        "next", "error", "complete", "asObservable",
    ],
    # ── dayjs - date library
    "dayjs": [
        "parse", "utc", "local", "isDayjs", "extend", "locale", "locales",
        "updateLocale", "customParseFormat", "advancedFormat", "badInput",
        "businessDay", "calendar", "customParseFormat", "dayOfYear",
        "duration", "isBetween", "isSameOrAfter", "isSameOrBefore",
        "isLeapYear", "min", "max", "objectUtil", "persistent",
        "pluralGetSet", "preParsePostFormat", "quarterOfYear", "relativeTime",
        "render", "subtract", "toArray", "toObject", "toJSON", "toISOString",
        "toDate", "valueOf", "unix", "millisecond", "milliseconds",
        "second", "seconds", "minute", "minutes", "hour", "hours",
        "date", "dates", "day", "days", "weekday", "weekdays",
        "month", "months", "quarter", "quarters", "year", "years",
        "january", "february", "march", "april", "may", "june", "july",
        "august", "september", "october", "november", "december",
        "monday", "tuesday", "wednesday", "thursday", "friday", "saturday",
        "sunday", "format", "get", "set", "startOf", "endOf", "add",
        "subtract", "diff", "asleep", "clone", "isBefore", "isAfter",
        "isSame", "isBetween", "isSameOrBefore", "isSameOrAfter",
        "isLeapYear", "isValid", "min", "max",
    ],
    # ── chalk - terminal string styling
    "chalk": [
        "rgb", "hsl", "hsv", "hwb", "cmyk", "ansi256", "hex",
        "keyword", "ansi", "ansiColors", "ansiBGColors",
        "level", "enabled", "supportsColor", "stdout", "stderr",
        "Constructor", "ChalkOptions", "ColorSupport",
        "reset", "bold", "dim", "italic", "underline", "inverse",
        "hidden", "strikethrough", "visible", "black", "red", "green",
        "yellow", "blue", "magenta", "cyan", "white", "gray", "grey",
        "brightBlack", "brightRed", "brightGreen", "brightYellow",
        "brightBlue", "brightMagenta", "brightCyan", "brightWhite",
        "bgBlack", "bgRed", "bgGreen", "bgYellow", "bgBlue",
        "bgMagenta", "bgCyan", "bgWhite", "bgBrightBlack", "bgBrightRed",
        "bgBrightGreen", "bgBrightYellow", "bgBrightBlue",
        "bgBrightMagenta", "bgBrightCyan", "bgBrightWhite",
        "stripColor", "supportsColor", "stdout", "stderr",
    ],
    # ── commander - CLI framework
    "Command": [
        "name", "version", "description", "execPath", "executableDir",
        "option", "requiredOption", "options", "getOptionValue",
        "getOptionValueComputed", "setOptionValue", "setOptionValueWithSource",
        "configureOption", "addOption", "removeOption", "replaceOption",
        "argument", "arguments", "positionals", "variadic", "parse",
        "parseAsync", "execute", "prepare", "addHelpText", "addHelpOption",
        "help", "helpOption", "addHelpOption", "helpInformation",
        "addHelpCommand", "configureHelp", "helpCommand", "showHelp",
        "showHelpAfterError", "error", "exitOverride", "exitCode",
        "usage", "usageDescription", "makeHelpArgument", "createHelp",
        "createOption", "createArgument", "createCommand", "createHelp",
        "createOption", "createArgument", "createCommand", "createHelp",
        "createHelp", "createOption", "createArgument", "createCommand",
        "configureOutput", "outputConfiguration", "success", "failure",
        "on", "listener", "listeners", "emit", "removeListener",
        "removeAllListeners", "setMaxListeners", "getMaxListeners",
        "disableColor", "enableColor", "enabled", "colorEnabled",
        "name", "version", "description", "execPath", "executableDir",
        "opts", "options", "args", "processedArgv", "parsedArgv",
    ],
    # ── zod - schema validation
    "z": [
        "string", "number", "bigint", "boolean", "date", "symbol", "undefined",
        "null", "NaN", "integer", "float", "nonNaN", "int", "natural", "positive",
        "nonpositive", "negative", "nonnegative", "enum", "nativeEnum",
        "literal", "any", "unknown", "never", "void", "void", "undefined",
        "array", "tuple", "object", "record", "map", "set", "function",
        "promise", "lazy", "intersection", "union", "discriminatedUnion",
        "nullable", "optional", "transform", "pipeline", "preprocess",
        "catch", "default", "refine", "superRefine", "transformer", "preprocess",
        "string", "number", "bigint", "boolean", "date", "symbol", "undefined",
        "null", "NaN", "integer", "float", "nonNaN", "int", "natural", "positive",
        "nonpositive", "negative", "nonnegative", "enum", "nativeEnum",
        "literal", "any", "unknown", "never", "void", "array", "tuple",
        "object", "record", "map", "set", "function", "promise", "lazy",
        "intersection", "union", "discriminatedUnion", "nullable", "optional",
        "transform", "pipeline", "preprocess", "catch", "default",
        "refine", "superRefine", "transformer", "preprocess",
    ],
    "ZodType": [
        "parse", "parseAsync", "safeParse", "safeParseAsync", "refine",
        "superRefine", "transform", "default", "catch", "optional", "nullable",
        "nullish", "array", "promise", "or", "and", "transform", "catch",
        "default", "describe", "isOptional", "isNullable", "parse",
        "parseAsync", "safeParse", "safeParseAsync", "refine", "superRefine",
        "transform", "default", "catch", "optional", "nullable", "nullish",
        "array", "promise", "or", "and", "transform", "catch", "default",
        "describe", "isOptional", "isNullable", "parse", "parseAsync",
    ],
    # ── Pino - logger
    "pino": [
        "pino", "logger", "Pino", "baseLogger", "child", "level", "silent",
        "fatal", "error", "warn", "info", "debug", "trace", "silent",
        "bindings", "setBindings", "flush", "flushSync", "child",
        "level", "silent", "fatal", "error", "warn", "info", "debug",
        "trace", "silent", "bindings", "setBindings", "flush", "flushSync",
        "child", "level", "silent", "fatal", "error", "warn", "info",
        "debug", "trace", "silent", "bindings", "setBindings", "flush",
        "pino-http", "pino-pretty", "pino-logflare", "pino-datadog",
        "pino-elasticsearch", "pino-pretty", "pino-logflare",
    ],
    # ── winston - logger
    "winston": [
        "createLogger", "Logger", "Transport", "TransportStream", "Logform",
        "format", "info", "colors", "configs", "exceptions", "rejections",
        "errors", "unhandled", "uncaught", "level", "levels", "exitOnError",
        "silent", "defaultMeta", "configure", "add", "remove", "clear",
        "child", "close", "log", "write", "profile", "startTimer",
        "error", "warn", "info", "http", "verbose", "debug", "silly",
        "level", "levels", "defaultMeta", "exitOnError", "silent",
        "configure", "add", "remove", "clear", "child", "close",
        "transports", "transport", "loggers", "add", "get", "has",
        "createLogger", "Logger", "Transport", "TransportStream", "Logform",
        "format", "info", "colors", "configs", "exceptions", "rejections",
        "errors", "unhandled", "uncaught", "level", "levels", "exitOnError",
        "silent", "defaultMeta", "configure", "add", "remove", "clear",
        "child", "close", "log", "write", "profile", "startTimer",
    ],
    # ── dotenv - env var loader
    "dotenv": [
        "config", "parse", "populate", "resolveConfig", "configAsync",
        "parseAsync", "resolveConfigAsync", "config", "parse",
        "populate", "resolveConfig", "configAsync", "parseAsync",
        "resolveConfigAsync", "config", "parse", "populate",
        "resolveConfig", "configAsync", "parseAsync", "resolveConfigAsync",
    ],
    # ── uuid - UUID generator
    "uuid": [
        "v1", "v3", "v4", "v5", "v6", "v7", "v8", "NIL", "validate",
        "version", "parse", "stringify", "v1", "v3", "v4", "v5",
        "v6", "v7", "v8", "NIL", "validate", "version", "parse",
        "stringify", "v1", "v3", "v4", "v5", "v6", "v7", "v8",
        "NIL", "validate", "version", "parse", "stringify",
        "NIL", "validate", "version", "parse", "stringify",
    ],
}
