"""Python stdlib, builtins, and popular library stubs for call resolution.

Contains stub definitions for Python standard library modules, built-in types,
and popular third-party libraries (networkx, numpy, etc.).
"""

from __future__ import annotations

_PYTHON_STUBS: dict[str, list[str]] = {
    # ── Built-in types ──────────────────────────────────────────────────

    "list": [
        "append", "extend", "insert", "remove", "pop", "clear", "index",
        "count", "sort", "reverse", "copy", "len", "iter", "__getitem__",
        "__setitem__", "__delitem__", "__contains__", "__iter__", "__len__",
    ],
    "dict": [
        "get", "setdefault", "pop", "popitem", "clear", "update", "keys",
        "values", "items", "fromkeys", "copy", "len", "iter", "__getitem__",
        "__setitem__", "__delitem__", "__contains__", "__iter__", "__len__",
    ],
    "str": [
        "upper", "lower", "strip", "lstrip", "rstrip", "replace", "split",
        "rsplit", "join", "startswith", "endswith", "find", "rfind", "index",
        "rindex", "count", "isdigit", "isalpha", "isalnum", "isspace",
        "isupper", "islower", "title", "capitalize", "swapcase", "zfill",
        "center", "ljust", "rjust", "partition", "rpartition", "expandtabs",
        "translate", "encode", "decode", "format", "format_map", "isdecimal",
        "isascii", "isprintable", "removesuffix", "removeprefix",
    ],
    "int": ["bit_length", "to_bytes", "from_bytes", "denominator", "numerator", "conjugate",
            "real", "imag", "__abs__", "__floor__", "__ceil__", "__round__"],
    "float": [
        "is_integer", "as_integer_ratio", "hex", "fromhex", "is_nan", "is_inf",
        "is_finite", "real", "imag",
    ],
    "set": [
        "add", "remove", "discard", "pop", "clear", "update", "intersection_update",
        "difference_update", "symmetric_difference_update", "union", "intersection",
        "difference", "symmetric_difference", "issubset", "issuperset", "isdisjoint",
        "copy", "len", "iter", "__contains__", "__iter__", "__len__",
    ],
    "frozenset": [
        "union", "intersection", "difference", "symmetric_difference",
        "issubset", "issuperset", "isdisjoint", "copy", "len", "iter",
        "__contains__", "__iter__", "__len__",
    ],
    "tuple": [
        "count", "index", "len", "iter", "__getitem__", "__contains__",
        "__iter__", "__len__",
    ],
    "bytes": [
        "decode", "encode", "upper", "lower", "strip", "split", "find",
        "index", "count", "hex", "fromhex", "join", "replace", "translate",
        "maketrans", "len", "iter", "__contains__", "__iter__", "__len__",
    ],
    "bytearray": [
        "decode", "encode", "upper", "lower", "strip", "split", "find",
        "index", "count", "hex", "fromhex", "join", "replace", "translate",
        "maketrans", "len", "iter", "__contains__", "__iter__", "__len__",
        "append", "extend", "insert", "remove", "pop", "clear",
    ],
    "bool": ["__and__", "__or__", "__xor__", "__rand__", "__ror__", "__rxor__"],
    "complex": [
        "real", "imag", "conjugate", "__abs__", "__add__", "__sub__",
        "__mul__", "__truediv__", "__floordiv__",
    ],
    "range": [
        "start", "stop", "step", "__len__", "__getitem__", "__contains__",
        "__iter__", "__reversed__", "index", "count",
    ],
    "slice": ["start", "stop", "step", "indices"],

    # ── Exception classes ───────────────────────────────────────────────

    "Exception": [
        "__init__", "args", "str", "__str__", "__repr__", "with_traceback",
        "__cause__", "__context__", "__suppress_context__", "__traceback__",
    ],
    "BaseException": [
        "__init__", "args", "__str__", "__repr__", "with_traceback",
        "__cause__", "__context__", "__suppress_context__", "__traceback__",
    ],
    "ValueError": ["__init__", "args", "str"],
    "KeyError": ["__init__", "args", "str", "__str__", "__repr__", "args"],
    "TypeError": ["__init__", "args", "str"],
    "IndexError": ["__init__", "args", "str"],
    "AttributeError": ["__init__", "args", "str"],
    "ImportError": ["__init__", "args", "str", "name", "path"],
    "ModuleNotFoundError": ["__init__", "args", "str", "name", "path"],
    "FileNotFoundError": ["__init__", "args", "str"],
    "PermissionError": ["__init__", "args", "str"],
    "OSError": [
        "__init__", "args", "str", "errno", "filename", "filename2", "strerror",
    ],
    "StopIteration": ["__init__", "args", "str", "value"],
    "GeneratorExit": ["__init__", "args", "str"],
    "SystemExit": ["__init__", "args", "str", "code"],
    "KeyboardInterrupt": ["__init__", "args", "str"],
    "RuntimeError": ["__init__", "args", "str"],
    "RecursionError": ["__init__", "args", "str"],
    "OverflowError": ["__init__", "args", "str"],
    "ZeroDivisionError": ["__init__", "args", "str"],
    "FloatingPointError": ["__init__", "args", "str"],
    "NotImplementedError": ["__init__", "args", "str"],
    "NotImplemented": ["__bool__", "__and__", "__or__", "__xor__"],
    "EnvironmentError": ["__init__", "args", "str", "errno", "filename", "strerror"],
    "IOError": ["__init__", "args", "str", "errno", "filename", "strerror"],
    "WindowsError": ["__init__", "args", "str", "errno", "filename", "strerror"],
    "BufferError": ["__init__", "args", "str"],
    "ArithmeticError": ["__init__", "args", "str"],
    "LookupError": ["__init__", "args", "str"],
    "AssertionError": ["__init__", "args", "str"],
    "EOFError": ["__init__", "args", "str"],
    "PendingDeprecationWarning": ["__init__", "args", "str"],
    "DeprecationWarning": ["__init__", "args", "str"],
    "FutureWarning": ["__init__", "args", "str"],
    "ImportWarning": ["__init__", "args", "str"],
    "SyntaxWarning": ["__init__", "args", "str"],
    "ResourceWarning": ["__init__", "args", "str"],
    "UserWarning": ["__init__", "args", "str"],
    "Warning": ["__init__", "args", "str"],
    "BytesWarning": ["__init__", "args", "str"],
    "UnicodeWarning": ["__init__", "args", "str"],
    "UnicodeError": ["__init__", "args", "str"],
    "UnicodeDecodeError": [
        "__init__", "args", "str", "encoding", "object", "start", "end", "reason",
    ],
    "UnicodeEncodeError": [
        "__init__", "args", "str", "encoding", "object", "start", "end", "reason",
    ],
    "UnicodeTranslateError": [
        "__init__", "args", "str", "object", "start", "end", "reason",
    ],
    "TabError": ["__init__", "args", "str"],
    "IndentationError": ["__init__", "args", "str"],
    "SyntaxError": [
        "__init__", "args", "str", "msg", "filename", "lineno", "offset", "text",
    ],
    "SystemError": ["__init__", "args", "str"],
    "ReferenceError": ["__init__", "args", "str"],
    "MemoryError": ["__init__", "args", "str"],
    "ConnectionError": ["__init__", "args", "str"],
    "BrokenPipeError": ["__init__", "args", "str"],
    "ConnectionAbortedError": ["__init__", "args", "str"],
    "ConnectionRefusedError": ["__init__", "args", "str"],
    "ConnectionResetError": ["__init__", "args", "str"],
    "TimeoutError": ["__init__", "args", "str"],
    "StopAsyncIteration": ["__init__", "args", "str"],
    "NotADirectoryError": ["__init__", "args", "str"],
    "IsADirectoryError": ["__init__", "args", "str"],
    "ProcessLookupError": ["__init__", "args", "str"],
    "ChildProcessError": ["__init__", "args", "str"],

    # ── Collections ─────────────────────────────────────────────────────

    "defaultdict": [
        "get", "setdefault", "pop", "popitem", "clear", "update",
        "keys", "values", "items", "copy", "len",
        "__getitem__", "__setitem__", "__delitem__", "__contains__",
        "__iter__", "__len__",
    ],
    "Counter": [
        "get", "setdefault", "pop", "popitem", "clear", "update",
        "keys", "values", "items", "copy", "len",
        "__getitem__", "__setitem__", "__delitem__", "__contains__",
        "__iter__", "__len__",
        "elements", "most_common", "subtract", "total",
        "count", "add", "remove",
    ],
    "OrderedDict": [
        "get", "setdefault", "pop", "popitem", "clear", "update",
        "keys", "values", "items", "copy", "len",
        "__getitem__", "__setitem__", "__delitem__", "__contains__",
        "__iter__", "__len__",
        "move_to_end", "__reversed__",
    ],
    "deque": [
        "append", "appendleft", "pop", "popleft", "extend", "extendleft",
        "rotate", "remove", "clear", "count", "insert", "index",
        "reverse", "copy", "len",
    ],

    # ── Type hints ──────────────────────────────────────────────────────

    "Optional": ["is_some", "is_none", "unwrap", "expect", "map", "and_then", "unwrap_or"],
    "Union": ["isinstance"],
    "Callable": ["__call__"],
    "Iterator": [
        "next", "iter", "__next__", "__iter__",
    ],
    "Generator": [
        "send", "throw", "close", "return",
    ],
    "Iterable": ["__iter__"],
    "Mapping": [
        "keys", "values", "items", "get", "pop", "popitem", "clear", "update",
        "copy", "len", "iter", "__getitem__", "__setitem__", "__delitem__",
        "__contains__", "__iter__", "__len__", "__reversed__",
    ],
    "Sequence": [
        "append", "extend", "insert", "remove", "pop", "clear", "index",
        "count", "sort", "reverse", "copy", "len", "iter",
        "__getitem__", "__setitem__", "__delitem__", "__contains__",
        "__iter__", "__len__", "__reversed__",
    ],

    # ── Stdlib modules ──────────────────────────────────────────────────

    "pathlib.Path": [
        "exists", "is_file", "is_dir", "is_symlink", "read_text", "read_bytes",
        "write_text", "write_bytes", "iterdir", "parent", "name", "stem",
        "suffix", "parts", "match", "resolve", "absolute", "relative_to",
        "with_suffix", "with_name", "joinpath", "glob", "rglob", "stat",
        "mkdir", "unlink", "rename", "replace", "touch", "chmod", "samefile",
        "as_posix", "as_uri", "write_text", "read_text", "read_bytes",
        "write_bytes", "readlink", "chmod", "cwd", "expanduser", "group",
        "hardlink_to", "home", "is_absolute", "iterdir", "lchmod", "link_to",
        "lstat", "owner", "parents", "rename", "replace", "rmdir",
        "symlink_to", "unlink", "with_name", "with_suffix", "suffixes",
        "is_reserved", "walk", "is_socket", "splitlines", "encode",
    ],
    "pathlib.PurePosixPath": [
        "exists", "is_file", "is_dir", "is_symlink", "read_text", "read_bytes",
        "write_text", "write_bytes", "iterdir", "parent", "name", "stem",
        "suffix", "parts", "match", "resolve", "absolute", "relative_to",
        "with_suffix", "with_name", "joinpath", "glob", "rglob", "stat",
        "mkdir", "unlink", "rename", "replace", "touch", "chmod", "samefile",
        "as_posix", "as_uri", "readlink", "chmod", "cwd", "expanduser",
        "group", "hardlink_to", "home", "is_absolute", "iterdir", "lchmod",
        "link_to", "lstat", "owner", "parents", "rename", "replace", "rmdir",
        "symlink_to", "unlink", "with_name", "with_suffix", "suffixes",
        "is_reserved", "walk", "is_socket", "splitlines", "encode",
    ],
    "os": [
        "path", "environ", "getenv", "setenv", "remove", "rename", "renames",
        "mkdir", "makedirs", "rmdir", "removedirs", "listdir", "scandir",
        "walk", "chdir", "getcwd", "getpid", "getppid", "getuid", "getgid",
        "execvp", "fork", "waitpid", "kill", "access", "stat", "lstat",
        "link", "symlink", "readlink", "umask", "truncate",
    ],
    "sys": [
        "argv", "exit", "version", "platform", "stdin", "stdout", "stderr",
        "path", "modules", "getsizeof", "setrecursionlimit", "getrecursionlimit",
        "getdefaultencoding", "settrace", "gettrace", "getprofile",
        "exc_info", "excepthook", "unraisablehook",
    ],
    "re": [
        "search", "match", "fullmatch", "findall", "finditer", "sub", "subn",
        "split", "compile", "escape", "pattern", "flags", "group", "groups",
        "groupdict", "start", "end", "span",
    ],
    "re.Match": [
        "group", "groups", "groupdict", "start", "end", "span", "lastgroup",
        "lastindex", "string", "__getitem__", "__len__", "re", "pos", "endpos",
    ],
    "json": [
        "loads", "dumps", "load", "dump", "JSONDecoder", "JSONEncoder",
        "JSONDecodeError",
    ],
    "logging": [
        "debug", "info", "warning", "warn", "error", "critical", "log",
        "getLogger", "basicConfig", "StreamHandler", "FileHandler",
        "Formatter", "Logger",
    ],
    "logging.Handler": [
        "handle", "emit", "makeRecord", "handleError", "handle", "close",
        "flush", "setLevel", "getEffectiveLevel", "isEnabledFor",
        "addFilter", "removeFilter", "filter", "format", "createRecord",
        "emit", "handle", "close", "flush", "acquire", "release",
        "level", "name", "parent", "propagate", "disabled",
    ],
    "logging.Logger": [
        "debug", "info", "warning", "error", "critical", "exception", "log",
        "addHandler", "removeHandler", "setLevel", "getEffectiveLevel",
        "isEnabledFor", "addFilter", "removeFilter", "filter",
        "makeRecord", "handle", "callHandlers", "callHandlers",
        "getChild", "handlers", "disabled", "manager", "name",
        "parent", "propagate", "level",
    ],
    "logging.StreamHandler": [
        "emit", "flush", "close", "createLock", "lock", "stream",
        "level", "name", "setLevel", "getEffectiveLevel",
    ],
    "logging.Formatter": [
        "format", "formatTime", "formatException", "converter",
        "datefmt", "style", "validate", "defaults", "useChildren",
        "_style", "_fmt",
    ],
    "logging.LoggerAdapter": [
        "process", "process", "debug", "info", "warning", "error", "critical",
        "exception", "log", "isEnabledFor", "findCaller", "makeRecord",
        "handle", "callHandlers", "getChild", "handlers",
        "disabled", "manager", "name", "parent", "propagate", "level",
    ],
    "logging.PlaceHolder": [
        "handlers", "disabled", "manager", "name", "parent", "propagate",
        "level", "debug", "info", "warning", "error", "critical",
        "exception", "log", "isEnabledFor", "findCaller", "makeRecord",
        "handle", "callHandlers",
    ],
    "logging.Manager": [
        "loggerDict", "disable", "disableCache", "cache",
        "getLogger", "getEffectiveLevel", "isEnabledFor",
    ],
    "dataclasses": [
        "dataclass", "field", "make_dataclass", "asdict", "astuple",
        "fields", "is_dataclass", "replace",
    ],
    "typing": [
        "Optional", "Union", "List", "Dict", "Set", "Tuple", "Sequence",
        "Mapping", "Iterator", "Generator", "Callable", "TypeVar", "Generic",
        "Any", "ClassVar", "Final", "Protocol", "runtime_checkable",
        "cast", "get_type_hints", "get_args", "get_origin",
        "Annotated", "Literal", "TypedDict",
    ],
    "collections": [
        "defaultdict", "Counter", "OrderedDict", "deque", "namedtuple",
        "ChainMap", "UserDict", "UserList", "UserString",
    ],
    "functools": [
        "lru_cache", "cache", "partial", "wraps", "partialmethod",
        "reduce", "total_ordering",
    ],
    "itertools": [
        "chain", "combinations", "combinations_with_replacement", "compress",
        "count", "cycle", "dropwhile", "filterfalse", "groupby", "islice",
        "permutations", "product", "repeat", "starmap", "takewhile",
        "tee", "zip_longest",
    ],
    "os.path": [
        "join", "exists", "isfile", "isdir", "islink", "isabs", "abspath",
        "relpath", "dirname", "basename", "splitext", "split", "commonpath",
        "realpath", "samefile", "getsize", "getmtime", "getctime", "lexists",
        "walk", "pardir", "sep", "altsep",
    ],
    "subprocess": [
        "run", "call", "check_output", "check_call", "Popen", "PIPE",
        "STDOUT", "CompletedProcess",
    ],
    "datetime": [
        "datetime", "date", "time", "timedelta", "timezone", "UTC",
        "now", "today", "fromtimestamp", "utcnow", "strptime", "strftime",
        "isoformat", "isocalendar", "weekday", "isoweekday", "replace",
        "timetz", "tzinfo", "tzname", "utcoffset", "dst", "timestamp",
    ],
    "hashlib": [
        "md5", "sha1", "sha256", "sha512", "new", "file_digest", "pbkdf2_hmac",
        "sha384", "sha3_256", "sha3_512", "sha3_224", "sha3_384", "blake2b", "blake2s",
        "hash", "digest_size", "block_size", "digest", "hexdigest", "update",
        "algorithms_guaranteed", "algorithms_available", "HMAC",
    ],
    "threading": [
        "Thread", "Lock", "RLock", "Semaphore", "Event", "Condition",
        "Barrier", "Timer", "BoundedSemaphore", "active_count",
        "enumerate", "current_thread", "main_thread",
    ],
    "contextlib": [
        "contextmanager", "suppress", "redirect_stdout", "redirect_stderr",
        "closing", "ExitStack", "AbstractContextManager", "AbstractAsyncContextManager",
    ],
    "unittest": [
        "TestCase", "main", "mock", "SkipTest", "skip", "skipIf", "skipUnless",
        "TextTestRunner", "TestSuite", "Loader", "Case", "Fail",
        "AssertRaisesContext", "FunctionTestCase",
    ],
    "unittest.mock": [
        "MagicMock", "Mock", "patch", "PropertyMock", "AsyncMock",
        "create_autospec", "mock_open", "ANY", "DEFAULT", "call", "sentinel",
        "seal", "reset_mock", "spec", "spec_set", "autospec",
    ],
    "argparse": [
        "ArgumentParser", "add_argument", "parse_args", "parse_known_args",
        "Namespace",
    ],
    "abc": [
        "abstractmethod", "ABCMeta", "ABCCollection", "ABCIterable",
        "ABCIterator", "ABCMappedCollection",
    ],
    "pytest": [
        "raises", "mark", "fixture", "parametrize", "approx", "tempdir",
        "tempfile", "skip", "xfail", "fail", "deprecated_call", "warns",
        "CaptureFixture", "MonkeyPatch",
    ],
    "fnmatch": [
        "fnmatch", "filter", "translate",
    ],
    "struct": [
        "pack", "unpack", "calcsize", "pack_into", "unpack_from", "error",
    ],
    "heapq": [
        "heappush", "heappop", "heapify", "heapreplace", "heappushpop",
        "nlargest", "nsmallest", "merge", "swapdown",
    ],
    "csv": [
        "reader", "writer", "DictReader", "DictWriter", "Sniffer", "register_dialect",
        "unregister_dialect", "get_dialect", "field_size_limit", "QUOTE_MINIMAL",
        "QUOTE_ALL", "QUOTE_NONNUMERIC", "QUOTE_NONE", "excel", "excel_tab",
        "unix", "writerows", "writeheader",
    ],
    "socket": [
        "socket", "AF_INET", "AF_INET6", "AF_UNIX", "SOCK_STREAM", "SOCK_DGRAM",
        "SOCK_RAW", "SOCK_SEQPACKET", "connect", "bind", "listen", "accept",
        "send", "recv", "sendall", "sendto", "recvfrom", "setsockopt",
        "getsockopt", "getpeername", "getsockname", "settimeout",
        "gettimeout", "close", "shutdown", "makefile", "dup",
        "create_connection", "gethostbyname", "gethostbyname_ex", "getservbyname",
        "getservbyport", "getprotobyname", "gaierror", "herror",
        "timeout", "error", "EBADF", "EINTR", "EAGAIN", "EWOULDBLOCK",
        "MSG_DONTWAIT", "MSG_OOB", "SO_REUSEADDR", "SO_KEEPALIVE",
        "SO_BROADCAST", "SO_LINGER", "SO_RCVBUF", "SO_SNDBUF",
        "SO_REUSEPORT", "SO_ATTACH_FILTER", "SO_DETACH_FILTER",
    ],
    "http.server": [
        "HTTPServer", "BaseHTTPRequestHandler", "SimpleHTTPRequestHandler",
        "CGIHTTPRequestHandler", "ThreadingHTTPServer", "serve_forever",
        "handle_request", "handle_one_request", "handle",
        "send_response", "send_header", "end_headers",
        "log_request", "log_error", "log_date_time_string",
        "do_GET", "do_HEAD", "do_POST", "do_PUT", "do_DELETE",
        "do_OPTIONS", "do_PATCH", "close_connection",
        "wfile", "rfile", "requestline", "request_version",
        "headers", "raw_requestline", "close_connection",
        "server_version", "sys_version", "error_message_format",
        "error_content_type", "version_string", "date_time_string",
        "response_class", "timeout", "request_queue_size",
        "allow_reuse_address", "bind_address", "server_name",
        "socket_type", "address_family", "RequestHandlerClass",
        "server_address", "ClientConnectionQueueSize",
    ],
    "socketserver": [
        "TCPServer", "UDPServer", "ThreadingTCPServer", "ThreadingUDPServer",
        "ForkingTCPServer", "ForkingUDPServer", "BaseServer",
        "TCPServer", "UDPServer", "UnixStreamServer", "UnixDatagramServer",
        "serve_forever", "handle_request", "handle_error", "server_close",
        "shutdown", "finish_request", "process_request", "process_request_thread",
        "process_request_fork", "get_request", "verify_request",
        "block_on_close", "connection_reuse", "request_queue_size",
        "address_family", "socket_type", "allow_reuse_address",
        "bind_address", "server_name", "server_port",
    ],
    "io": [
        "BytesIO", "StringIO", "FileIO", "BufferedReader", "BufferedWriter",
        "BufferedRandom", "BufferedRWPair", "TextIOWrapper",
        "open", "DEFAULT_BUFFER_SIZE", "UnsupportedOperation", "RawIOBase",
        "BufferedIOBase", "TextIOBase", "IOBase", "SEEK_SET", "SEEK_CUR",
        "SEEK_END", "read", "write", "readable", "writable", "seekable",
        "readinto", "readline", "readlines", "seek", "tell", "truncate",
        "close", "flush", "isatty", "detach", "read1", "peek", "readinto1",
    ],
    "concurrent.futures": [
        "ThreadPoolExecutor", "ProcessPoolExecutor", "Future", "Executor",
        "as_completed", "wait", "first_completed", "ALL_COMPLETED",
        "submit", "map", "shutdown", "__enter__", "__exit__",
        "result", "exception", "add_done_callback", "cancel",
        "cancelled", "running", "done", "set_result", "set_exception",
        "get_loop", "_thread_local", "_work_queue", "_shutdown",
        "max_workers", "thread_name_prefix", "initializer", "initargs",
    ],
    "importlib": [
        "import_module", "reload", "invalidate_caches", "util",
        "machinery", "bootstrap", "bootstrap_external",
        "abc", "find_spec", "exec_module", "module_from_spec",
        "spec_from_file_location", "module_from_spec", "exec_module",
        "loader_state", "ModuleSpec", "find_spec", "loader_state",
        "init_cache", "importlib.abc", "importlib.machinery",
        "MetaPathFinder", "PathEntryFinder", "Loader", "ResourceReader",
        "InvalidateCachesFinder", "reload", "import_module",
        "util", "find_spec", "module_from_spec", "exec_module",
        "original_import",
    ],
    "warnings": [
        "warn", "filterwarnings", "simplefilter", "catch_warnings",
        "showwarning", "showwarning", "formatwarning", "warn_explicit",
        "warn_explicit", "catch_warnings", "resetwarnings", "filters",
        "defaultaction", "oncepermodule", "module", "once",
    ],
    "time": [
        "time", "sleep", "clock", "monotonic", "perf_counter",
        "perf_counter_ns", "process_time", "process_time_ns",
        "datetime", "strftime", "strptime", "timezone", "altzone",
        "daylight", "get_clock_info", "gmtime", "localtime",
        "mktime", "timezone", "tzname", "time", "clock",
        "monotonic", "monotonic_ns", "perf_counter", "perf_counter_ns",
        "process_time", "process_time_ns", "sleep", "strftime",
        "strptime", "thread_time", "thread_time_ns", "time",
        "time_ns", "timer", "get_clock_info", "gmtime", "localtime",
        "mktime", "strftime", "strptime", "timezone", "tzname",
        "daylight", "altzone", "get_clock_info",
    ],
    "urllib.parse": [
        "urlparse", "urlsplit", "urljoin", "urlencode", "quote", "quote_plus",
        "unquote", "unquote_plus", "urlunparse", "urlunsplit", "parse_qs",
        "parse_qsl", "url2pathname", "pathname2url", "quote_from_bytes",
        "urlencode", "parse_qs", "parse_qsl", "url2pathname",
        "pathname2url", "quote", "quote_plus", "unquote", "unquote_plus",
        "urlparse", "urlsplit", "urljoin", "urlunparse", "urlunsplit",
        "ParseResult", "SplitResult", "DefragResult", "DefragResultBytes",
        "ParseResultBytes", "SplitResultBytes", "Params",
    ],
    "html.parser": [
        "HTMLParser", "HTMLParseError", "feed", "close", "goahead",
        "reset", "handle_data", "handle_starttag", "handle_endtag",
        "handle_startendtag", "handle_comment", "handle_decl", "handle_pi",
        "handle_entityref", "handle_charref", "unescape",
        "parser", "rawdata", "goahead", "reset", "feed", "close",
        "goahead", "handle_data", "handle_starttag", "handle_endtag",
        "handle_startendtag", "handle_comment", "handle_decl",
        "handle_pi", "handle_entityref", "handle_charref", "unescape",
    ],
    "sqlite3": [
        "connect", "Connection", "Cursor", "Row", "Parametrized", "OperationalError",
        "DatabaseError", "IntegrityError", "InterfaceError", "ProgrammingError",
        "NotSupportedError", "Error", "Warning", "register_adapter",
        "register_converter", "enable_callback", "disable_callback",
        "check_same_thread", "isolation_level", "timeout", "detect_types",
        "commit", "rollback", "close", "execute", "executemany",
        "executescript", "fetchone", "fetchall", "fetchmany",
        "rowcount", "lastrowid", "connection", "description",
        "arraysize", "close", "execute", "executemany", "executescript",
        "fetchone", "fetchall", "fetchmany", "rowcount", "lastrowid",
    ],
    "html": [
        "unescape", "escape", "Parser", "HTMLParser", "HTML5Parser",
        "HTMLParser", "HTMLParseError", "feed", "close", "goahead",
        "reset", "handle_data", "handle_starttag", "handle_endtag",
        "handle_startendtag", "handle_comment", "handle_decl", "handle_pi",
        "handle_entityref", "handle_charref",
    ],
    "copy": [
        "copy", "deepcopy", "CopyError",
        "copy", "deepcopy",
    ],
    "builtins": [
        "chr", "ord", "len", "range", "enumerate", "zip", "map", "filter",
        "sorted", "reversed", "any", "all", "sum", "min", "max", "abs",
        "round", "int", "float", "str", "list", "dict", "set", "tuple",
        "bool", "bytes", "bytearray", "memoryview", "frozenset",
        "property", "staticmethod", "classmethod", "super", "type",
        "object", "isinstance", "issubclass", "hasattr", "getattr",
        "setattr", "delattr", "repr", "hash", "id", "dir", "vars",
        "help", "iter", "next", "slice", "format", "exec", "eval",
        "compile", "open", "print", "input", "breakpoint", "ascii",
        "bin", "oct", "hex", "pow", "divmod", "globals", "locals",
        "callable", "delattr", "setattr", "getattr", "hasattr",
        "issubclass", "isinstance", "type", "super", "classmethod",
        "staticmethod", "property",
    ],

    # ── NumPy ───────────────────────────────────────────────────────────

    "numpy": [
        "array", "zeros", "ones", "empty", "full", "arange", "linspace",
        "logspace", "eye", "identity", "diag", "copy", "asarray", "asanyarray",
        "fromiter", "frombuffer", "fromfile", "fromstring", "from_dlpack",
        "convert_to_integer", "sort", "argsort", "partition", "argpartition",
        "unique", "intersect1d", "union1d", "setdiff1d", "setxor1d",
        "in1d", "isin", "any", "all", "count_nonzero",
        "sum", "nansum", "prod", "nanprod", "mean", "nanmean",
        "std", "nanstd", "var", "nanvar", "min", "nanmin", "max", "nanmax",
        "argmin", "argmax", "nanargmin", "nanargmax",
        "median", "percentile", "nanpercentile", "quantile", "nanquantile",
        "diff", "ediff1d", "gradient", "cross", "trapz", "cumsum", "nancumsum",
        "cumprod", "nancumprod", "clip", "repeat", "tile", "rot90",
        "insert", "delete", "append", "resize", "searchsorted", "extract",
        "put", "putmask", "choose", "compress", "round", "rint", "fix",
        "trunc", "floor", "ceil", "log", "log10", "log2", "log1p", "logaddexp",
        "logaddexp2", "exp", "exp2", "expm1", "sinc", "isposinf", "isneginf",
        "isfinite", "isinf", "isnan", "isnat", "signbit", "cbrt", "negative",
        "positive", "absolute", "fabs", "sign", "heaviside", "conj",
        "conjugate", "square", "sqrt", "reciprocal", "divide", "float_power",
        "power", "multiply", "matmul", "subtract", "true_divide", "floor_divide",
        "mod", "fmod", "modf", "remainder", "divmod", "greater", "greater_equal",
        "less", "less_equal", "equal", "not_equal", "logical_and", "logical_or",
        "logical_xor", "logical_not", "maximum", "minimum", "fmax", "fmin",
        "where", "select", "piecewise", "copyto", "inner", "outer",
        "tensordot", "einsum", "dot", "vdot", "multi_dot", "matvec", "vecmat",
        "int8", "int16", "int32", "int64", "uint8", "uint16", "uint32", "uint64",
        "float16", "float32", "float64", "complex64", "complex128",
        "bool_", "str_", "bytes_", "object_",
        "intp", "uintp", "longdouble", "cfloat", "cdouble", "csingle",
        "intc", "uintc", "int_", "longlong", "ulonglong",
        "ndarray", "dtype", "vectorize", "broadcast", "nditer",
        "newaxis", "index_exp", "ogrid", "mgrid", "r_", "c_",
        "NaN", "nan", "Inf", "inf", "Infinity", "infty", "PINF", "NINF",
        "e", "euler_gamma", "pi", "e", "tau", "inf", "nan",
        "meshgrid", "indices", "ogrid", "mgrid", "r_", "c_",
        "ndim", "shape", "size", "dtype", "T", "real", "imag",
        "base", "data", "itemsize", "nbytes", "strides", "flags",
        "reshape", "ravel", "flatten", "transpose", "swapaxes", "rollaxis",
        "moveaxis", "squeeze", "expand_dims", "repeat", "choose", "compress",
        "clip", "round", "astype", "view", "copy", "tobytes", "tofile",
        "tolist", "item", "sum", "nansum", "prod", "nanprod", "mean",
        "nanmean", "std", "nanstd", "var", "nanvar", "min", "nanmin",
        "max", "nanmax", "argmin", "argmax", "cumsum", "nancumsum",
        "cumprod", "nancumprod", "all", "any", "ptp", "searchsorted",
        "put", "putmask", "fill", "itemset", "shape", "ndim", "size",
        "dtype", "T", "real", "imag", "base", "data", "itemsize", "nbytes",
        "strides", "flags",
        "__getitem__", "__setitem__", "__iter__", "__len__",
    ],
    "ndarray": [
        "__getitem__", "__setitem__", "__iter__", "__len__",
        "reshape", "ravel", "flatten", "transpose", "swapaxes", "rollaxis",
        "moveaxis", "squeeze", "expand_dims", "repeat", "choose", "compress",
        "clip", "round", "astype", "view", "copy", "tobytes", "tofile",
        "tolist", "item", "sum", "nansum", "prod", "nanprod", "mean",
        "nanmean", "std", "nanstd", "var", "nanvar", "min", "nanmin",
        "max", "nanmax", "argmin", "argmax", "cumsum", "nancumsum",
        "cumprod", "nancumprod", "all", "any", "ptp", "searchsorted",
        "put", "putmask", "fill", "itemset", "shape", "ndim", "size",
        "dtype", "T", "real", "imag", "base", "data", "itemsize", "nbytes",
        "strides", "flags",
    ],
    "random": [
        "rand", "randn", "randint", "random", "random_sample", "sample",
        "choice", "bytes", "uniform", "normal", "standard_normal",
        "standard_t", "beta", "chisquare", "exponential", "gamma",
        "geometric", "gumbel", "hypergeometric", "laplace", "logistic",
        "lognormal", "logseries", "multinomial", "multivariate_normal",
        "negative_binomial", "noncentral_chisquare", "noncentral_f",
        "pareto", "poisson", "power", "rayleigh", "triangular", "uniform",
        "vonmises", "wald", "weibull", "zipf", "seed", "RandomState",
        "default_rng", "Generator", "BitGenerator", "MT19937", "PCG64",
        "SFC64", "Philox", "ThreeFry", "SetState", "get_state", "set_state",
        "bit_generator", "seed", "permutation", "shuffle", "integers",
        "standard_exponential", "standard_gamma", "standard_cauchy",
        "standard_pareto",
    ],
    "dtype": [
        "name", "str", "itemsize", "char", "kind", "num", "base", "item",
        "newbyteorder", "isbuiltin", "isnative", "isalignedstruct",
    ],
    "vectorize": [
        "__call__", "signature", "otypes", "nin", "nout", "nargs",
    ],

    # ── Third-party / external libraries ────────────────────────────────

    "SentenceTransformer": [
        "__init__", "encode", "transform", "forward", "get_sentence_features",
        "get_word_embeddings", "get_word_embedding_dimension", "get_max_seq_length",
        "get_sentence_pair_embedding_dimensions", "tokenizer", "model_card_data",
        "card_data", "device", "prompts", "default_prompt_name", "save",
        "load", "eval", "train", "fit", "evaluate", "predict", "predict_proba",
    ],
    "HTMLParser": [
        "feed", "close", "goahead", "reset", "handle_data", "handle_starttag",
        "handle_endtag", "handle_startendtag", "handle_comment", "handle_decl",
        "handle_pi", "handle_entityref", "handle_charref", "unescape",
    ],
    "HTTPServer": [
        "serve_forever", "handle_request", "handle_one_request", "handle",
        "server_close", "shutdown", "finish_request", "process_request",
        "process_request_thread", "process_request_fork", "get_request",
        "verify_request", "block_on_close", "connection_reuse",
        "request_queue_size", "address_family", "socket_type",
        "allow_reuse_address", "bind_address", "server_name",
        "server_port", "server_address", "ClientConnectionQueueSize",
    ],
    "Popen": [
        "__init__", "poll", "wait", "communicate", "send_signal", "terminate",
        "kill", "stdin", "stdout", "stderr", "pid", "returncode", "args",
        "stdin", "stdout", "stderr", "pid", "returncode", "args",
        "communicate", "poll", "wait", "send_signal", "terminate", "kill",
    ],
    "ThreadPoolExecutor": [
        "__init__", "submit", "map", "shutdown", "__enter__", "__exit__",
        "result", "exception", "add_done_callback", "cancel",
        "cancelled", "running", "done", "set_result", "set_exception",
        "get_loop", "_thread_local", "_work_queue", "_shutdown",
        "max_workers", "thread_name_prefix", "initializer", "initargs",
    ],
    "MagicMock": [
        "__call__", "__init__", "__repr__", "__str__", "__eq__", "__ne__",
        "__lt__", "__le__", "__gt__", "__ge__", "__hash__", "__bool__",
        "__iter__", "__len__", "__getitem__", "__setitem__", "__delitem__",
        "__contains__", "__enter__", "__exit__", "__await__",
        "assert_called", "assert_called_once", "assert_called_with",
        "assert_called_once_with", "assert_has_calls", "assert_any_call",
        "reset_mock", "configure_mock", "mock_add_spec", "spec_set",
        "side_effect", "return_value", "call_count", "call_args", "call_args_list",
        "method_calls", "mock_calls", "kwargs", "args", "return_value",
    ],
    "Query": [
        "__init__", "execute", "next", "reset", "dump", "match", "captures",
        "captures_at", "named_captures", "named_capture_names", "patterns",
        "pattern_count", "node_count", "text", "byte_range", "range",
        "node", "parent", "child", "field", "named_field", "type",
        "is_named", "is_missing", "descendant_for_point_in_range",
        "named_descendant_for_point_in_range",
    ],
    "QueryCursor": [
        "__init__", "execute", "next", "reset", "dump", "match", "captures",
        "captures_at", "named_captures", "named_capture_names", "patterns",
        "pattern_count", "node_count", "text", "byte_range", "range",
        "node", "parent", "child", "field", "named_field", "type",
        "is_named", "is_missing", "descendant_for_point_in_range",
        "named_descendant_for_point_in_range",
    ],
    "TreeSitterLanguage": [
        "__init__", "parse", "parse_string", "parse_bytes", "root_node",
        "root_string", "root_bytes", "edit", "version", "name",
        "query", "language", "node", "tree", "parser",
    ],
    "RustAnalyzerOptions": [
        "__init__", "rustup_path", "cargo_target_dir", "check_workspace",
        "check", "features", "all_features", "no_default_features",
        "use_configuration_file", "configuration_file", "settings_file",
        "settings_override", "load_hierarchical_settings",
    ],
    "WeightedPath": [
        "__init__", "nodes", "edges", "weight", "length", "cost",
        "is_valid", "is_feasible", "is_optimal", "dominates",
    ],
    "PythonFilter": [
        "__init__", "process", "handle", "filter", "emit", "close",
        "flush", "setLevel", "getEffectiveLevel", "isEnabledFor",
        "addFilter", "removeFilter", "format", "createRecord",
    ],
    "Client": [
        "__init__", "connect", "disconnect", "send", "receive", "close",
        "sendall", "recv", "setsockopt", "getsockopt", "getpeername",
        "getsockname", "settimeout", "gettimeout", "shutdown", "makefile",
        "dup", "create_connection", "gethostbyname", "gethostbyname_ex",
    ],
    "Confidence": [
        "__init__", "value", "name", "description", "is_high", "is_medium",
        "is_low", "is_uncertain", "is_definite", "is_probable",
        "is_likely", "is_possible", "is_impossible",
    ],
    "PathQuery": [
        "__init__", "execute", "next", "reset", "dump", "match", "captures",
        "captures_at", "named_captures", "named_capture_names", "patterns",
        "pattern_count", "node_count", "text", "byte_range", "range",
        "node", "parent", "child", "field", "named_field", "type",
        "is_named", "is_missing", "descendant_for_point_in_range",
        "named_descendant_for_point_in_range",
    ],
    "ImpactQuery": [
        "__init__", "execute", "next", "reset", "dump", "match", "captures",
        "captures_at", "named_captures", "named_capture_names", "patterns",
        "pattern_count", "node_count", "text", "byte_range", "range",
        "node", "parent", "child", "field", "named_field", "type",
        "is_named", "is_missing", "descendant_for_point_in_range",
        "named_descendant_for_point_in_range",
    ],
    "LanguageRegistry": [
        "__init__", "register", "unregister", "get", "list", "has",
        "supported", "supported_languages", "detect", "detect_language",
        "extract", "extract_file", "extract_string", "extract_code",
    ],
    "ExtractionPipeline": [
        "__init__", "run", "execute", "process", "extract", "parse",
        "build", "add_step", "remove_step", "get_steps", "run_pipeline",
        "execute_pipeline", "process_pipeline", "extract_pipeline",
    ],
    "GraphStore": [
        "__init__", "add_node", "add_edge", "remove_node", "remove_edge",
        "get_node", "get_edge", "has_node", "has_edge", "nodes",
        "edges", "adj", "adjacency", "degree", "in_degree", "out_degree",
        "subgraph", "copy", "to_directed", "to_undirected",
        "clear", "clear_edges", "update", "compose",
        "union", "intersection", "difference",
        "reverse", "density", "is_directed", "is_connected",
        "is_strongly_connected", "number_connected_components",
        "connected_components", "weakly_connected_components",
        "strongly_connected_components", "node_connected_component",
        "degree_histogram", "order", "size", "degree_view",
    ],
    "CommunityOptions": [
        "__init__", "resolution", "weight", "threshold", "max_communities",
        "min_communities", "seed", "n_iterations", "random_state",
        "verbose", "progress_bar", "timeout", "max_tries",
        "merge_threshold", "split_threshold", "quality_threshold",
    ],
    "EmbeddingIndex": [
        "__init__", "add", "remove", "query", "search", "index",
        "build", "train", "fit", "predict", "transform", "embed",
        "encode", "decode", "retrieve", "update", "delete",
        "get_embedding", "get_vector", "get_distance", "get_similarity",
        "get_neighbors", "get_knn", "get_ann", "get_faiss",
    ],
    "ExternalEmbeddingConfig": [
        "__init__", "provider", "model", "dimensions", "batch_size",
        "timeout", "max_retries", "api_key", "api_url", "api_version",
        "embedding_type", "normalize", "pooling", "truncate",
        "cache", "cache_dir", "cache_ttl", "cache_size",
    ],
    "NetworkX": [
        "Graph", "DiGraph", "MultiGraph", "MultiDiGraph",
        "add_node", "add_nodes_from", "remove_node", "remove_nodes_from",
        "add_edge", "add_edges_from", "remove_edge", "remove_edges_from",
        "edges", "nodes", "number_of_edges", "number_of_nodes",
        "has_node", "has_edge", "neighbors", "predecessors", "successors",
        "adj", "adjacency", "degree", "in_degree", "out_degree",
        "subgraph", "copy", "to_directed", "to_undirected",
        "clear", "clear_edges", "update", "compose",
        "union", "intersection", "difference",
        "reverse", "density", "is_directed", "is_connected",
        "is_strongly_connected", "number_connected_components",
        "connected_components", "weakly_connected_components",
        "strongly_connected_components", "node_connected_component",
        "degree_histogram", "order", "size", "degree_view",
        "add_weighted_edges_from", "add_path", "add_cycle", "add_star",
        "get_edge_data", "pred",
        "is_empty", "is_multigraph", "clear_edges",
    ],

    # ── networkx (kept for backward compatibility) ──────────────────────

    "networkx": [
        "Graph", "DiGraph", "MultiGraph", "MultiDiGraph",
        "add_node", "add_nodes_from", "remove_node", "remove_nodes_from",
        "add_edge", "add_edges_from", "remove_edge", "remove_edges_from",
        "edges", "nodes", "number_of_edges", "number_of_nodes",
        "has_node", "has_edge", "neighbors", "predecessors", "successors",
        "adj", "adjacency", "degree", "in_degree", "out_degree",
        "subgraph", "copy", "to_directed", "to_undirected",
        "clear", "clear_edges", "update", "compose",
        "union", "intersection", "difference",
        "reverse", "density", "is_directed",
        "order", "size", "degree_view",
        "connected_components", "weakly_connected_components",
        "strongly_connected_components", "node_connected_component",
        "degree_histogram",
        "add_weighted_edges_from", "add_path", "add_cycle", "add_star",
        "get_edge_data", "pred",
        "is_empty", "is_multigraph", "clear_edges",
    ],
}
