"""Rust stdlib and common crate stubs for call resolution.

Contains stub definitions for Rust standard library types and commonly
used crates (tokio, serde_json, tracing, etc.).
"""

from __future__ import annotations

_RUST_STUBS: dict[str, list[str]] = {
    "Vec": [
        "push", "pop", "len", "is_empty", "insert", "remove", "get", "get_mut",
        "clear", "reserve", "resize", "truncate", "retain", "sort", "sort_by",
        "sort_by_key", "contains", "swap", "split_off", "drain", "extend",
        "from", "into_iter", "iter", "iter_mut", "as_slice", "as_mut_slice",
        "capacity", "with_capacity", "new", "dedup", "first", "first_mut",
        "last", "last_mut", "splice", "append", "to_vec", "as_ptr", "as_mut_ptr",
        "try_push", "shrink_to", "shrink_to_fit", "dedup_by", "dedup_by_key",
        "resize_with", "into_boxed_slice",
    ],
    "HashMap": [
        "get", "get_mut", "insert", "remove", "len", "is_empty", "contains_key",
        "clear", "entry", "remove_entry", "keys", "values", "values_mut", "iter",
        "iter_mut", "extend", "reserve", "shrink_to_fit", "get_or_insert",
        "get_or_insert_with", "or_insert", "or_insert_with", "default", "from",
        "from_iter", "into_keys", "into_values", "retain", "drain",
        "swap_remove", "capacity",
    ],
    "BTreeMap": [
        "get", "get_mut", "insert", "remove", "entry", "contains_key", "keys",
        "values", "values_mut", "iter", "iter_mut", "extend", "new", "from",
        "from_iter", "len", "is_empty", "clear", "first_entry", "last_entry",
        "floor_entry", "ceiling_entry", "range", "get_key_value", "retain", "drain",
    ],
    "HashSet": [
        "insert", "remove", "contains", "get", "len", "is_empty", "iter", "clear",
        "extend", "new", "from", "from_iter", "reserve", "shrink_to_fit",
        "difference", "symmetric_difference", "intersection", "union", "swap_remove",
        "extract_if", "drain", "retain",
    ],
    "VecDeque": [
        "push_back", "push_front", "pop_back", "pop_front", "get", "get_mut",
        "len", "is_empty", "front", "back", "front_mut", "back_mut", "clear",
        "iter", "iter_mut", "new", "reserve", "with_capacity", "truncate",
        "rotate_left", "rotate_right", "contains", "insert", "remove", "drain",
        "append", "extract_if", "retain",
    ],
    "String": [
        "new", "from", "to_string", "to_owned", "push", "push_str", "pop", "clear",
        "len", "is_empty", "capacity", "reserve", "resize", "truncate", "insert",
        "remove", "replace_range", "split_off", "drain", "as_str", "as_mut_str",
        "as_bytes", "as_mut_vec", "retain", "shrink_to_fit", "shrink_to",
        "extend", "from_utf8", "from_utf8_lossy", "from_utf16", "from_utf16_lossy",
        "from_str", "into_boxed_str", "into_bytes", "to_lowercase", "to_uppercase",
        "trim", "trim_start", "trim_end", "trim_matches", "strip_prefix",
        "strip_suffix", "split", "splitn", "rsplit", "lines", "chars",
        "bytes", "is_ascii", "to_ascii_lowercase", "to_ascii_uppercase",
    ],
    "Option": [
        "is_some", "is_none", "Some", "None", "unwrap", "expect", "map",
        "and_then", "or_else", "ok_or", "ok_or_else", "unwrap_or",
        "unwrap_or_default", "unwrap_or_else", "as_ref", "as_mut", "as_deref",
        "filter", "transpose", "and", "or", "iter", "as_ref_and_then",
    ],
    "Result": [
        "ok", "err", "unwrap", "expect", "map", "map_err", "and_then", "or_else",
        "unwrap_or", "unwrap_or_else", "unwrap_or_default", "as_ref", "as_mut",
        "is_ok", "is_err", "transpose", "ok_or", "ok_or_else",
    ],
    "Iterator": [
        "next", "nth", "last", "count", "size_hint", "fold", "for_each", "map",
        "filter", "filter_map", "flat_map", "collect", "cloned", "copied",
        "enumerate", "zip", "chain", "fuse", "by_ref", "scan", "flatten", "unzip",
        "try_fold", "try_for_each", "peekable", "skip", "take", "skip_while",
        "take_while", "step_by", "cycle", "repeat", "repeat_with", "intersperse",
        "rev", "sum", "product", "max", "min", "max_by", "min_by", "max_by_key",
        "min_by_key", "any", "all", "find", "position", "rposition",
        "partition", "exactly_one",
    ],
    "Slice": [
        "iter", "iter_mut", "len", "is_empty", "get", "get_mut", "split",
        "split_mut", "splitn", "rsplit", "rsplitn", "chunks", "chunks_mut",
        "windows", "first", "first_mut", "last", "last_mut", "swap", "contains",
        "starts_with", "ends_with", "sort", "sort_by", "sort_by_key",
        "sort_unstable", "sort_unstable_by", "sort_unstable_by_key",
        "partition", "binary_search", "binary_search_by", "binary_search_by_key",
        "to_vec", "to_owned", "as_ptr", "as_mut_ptr", "get_unchecked",
    ],
    "Path": [
        "join", "parent", "file_name", "file_stem", "extension", "strip_prefix",
        "starts_with", "ends_with", "to_str", "to_path_buf", "components", "iter",
        "display", "as_path", "as_os_str", "push", "pop", "into_os_string",
    ],
    "PathBuf": [
        "new", "push", "pop", "as_path", "to_path_buf", "to_str", "as_os_str",
        "into_os_string", "file_name", "file_stem", "extension", "parent",
        "join", "is_absolute", "is_relative", "exists",
    ],
    "Duration": [
        "as_secs", "as_nanos", "checked_add", "checked_sub", "checked_mul",
        "saturating_add", "saturating_sub", "saturating_mul", "from_secs",
        "from_millis", "from_nanos", "from_micros", "is_zero", "new",
    ],
    "Box": [
        "new", "into_raw", "from_raw", "into", "as_ref", "as_mut", "deref",
        "into_boxed_slice", "unwrap", "leak", "downcast", "downcast_mut",
    ],
    "Arc": [
        "new", "clone", "try_unwrap", "into_raw", "from_raw", "as_ptr",
        "strong_count", "weak_count", "downgrade", "upgrade", "get_mut",
    ],
    "Mutex": [
        "new", "lock", "try_lock", "get_mut", "into_inner", "into_lock_guard",
    ],
    "RwLock": [
        "new", "read", "try_read", "write", "try_write", "get_mut",
        "into_inner", "into_read_guard", "into_write_guard",
    ],
    "Cell": ["new", "get", "set", "replace", "take", "into_inner"],
    "RefCell": [
        "new", "borrow", "borrow_mut", "try_borrow", "try_borrow_mut",
        "into_inner", "borrow_check",
    ],
    "AtomicUsize": [
        "new", "load", "store", "fetch_add", "fetch_sub", "fetch_and",
        "fetch_or", "fetch_xor", "swap", "compare_exchange", "compare_exchange_weak",
    ],
    "AtomicBool": [
        "new", "load", "store", "fetch_and", "fetch_or", "fetch_xor",
        "swap", "compare_exchange", "compare_exchange_weak",
    ],
    "FromStr": ["from_str"],
    "io": [
        "read", "read_to_end", "read_to_string", "read_exact", "write",
        "write_all", "flush", "write_fmt", "BufRead", "Read", "Write",
    ],
    "env": ["args", "current_dir", "set_current_dir", "temp_dir", "var", "var_os",
            "vars", "vars_os", "set_var", "remove_var", "current_exe", "var"],
    "fs": [
        "read", "read_to_string", "write", "create", "create_dir", "create_dir_all",
        "remove_dir", "remove_dir_all", "remove_file", "rename", "copy", "metadata",
        "symlink_metadata", "read_dir", "set_permissions", "canonicalize", "exists",
        "write_bytes", "read_bytes",
    ],
    "time": ["now", "duration_since", "elapsed"],
    "serde_json": [
        "Value", "to_string", "to_string_pretty", "to_value", "from_str",
        "from_slice", "from_reader", "to_writer", "from_value", "Map", "Number",
        "from_reader", "to_writer",
    ],
    "tokio": ["spawn", "task"],
    "tracing": [
        "info", "debug", "warn", "error", "trace", "info_span", "debug_span",
        "warn_span", "error_span", "trace_span", "instrument",
    ],
    "anyhow": ["Result", "Context", "bail", "ensure"],
    "regex": [
        "Regex", "new", "find", "find_iter", "captures", "captures_iter",
        "is_match", "replace", "replace_all", "split", "splitn",
        "RegexSet", "no_lookahead",
    ],
    "walkdir": ["WalkDir", "new", "into_iter"],
    "rayon": [
        "join", "scope", "iter", "scope", "into_iter", "scope",
        "IntoParallelIterator", "IntoParallelRefIterator", "ParallelIterator",
        "ParallelDrainFull",
    ],

    # ── Popular Rust crates ───────────────────────────────────────────

    # ── axum - web framework
    "axum": [
        "Router", "Route", "handler", "get", "post", "put", "delete",
        "patch", "options", "head", "trace", "any", "merge", "nest",
        "nest_service", "route", "on", "on_service", "fallback",
        "fallback_service", "layer", "service", "expand", "with", "with_state",
        "without", "into_make_service", "into_make_service_with_connect_info",
        "serve", "bind", "bind_with_graceful_shutdown", "bind_addrs",
        "axum_server", "serve_with_graceful_shutdown", "serve_with_graceful_cancel",
        "HttpServer", "Server", "listen", "accept", "graceful_shutdown",
        "State", "Extension", "Json", "Form", "Query", "Path", "Header",
        "Cookie", "CookieJar", "Origin", "Method", "Uri", "Headers",
        "Request", "Response", "StatusCode", "Body", "axum::body", "HttpBody",
    ],
    # ── actix-web - web framework
    "actix_web": [
        "App", "HttpServer", "web", "guard", "guarder", "scope",
        "resource", "route", "service", "resource", "default_service",
        "wrap", "wrap_fn", "middleware", "dev", "Resource", "Route",
        "Guard", "Guarder", "Scope", "Resource", "Route",
        "HttpRequest", "HttpResponse", "Error", "Result",
        "Body", "Bytes", "Json", "Form", "Query", "Path", "Data",
        "Config", "Error", "web::Json", "web::Form", "web::Query",
        "web::Path", "web::Data", "web::Bytes", "web::BytesMut",
        "web::block", "web::bytes", "web::json", "web::form", "web::query",
        "web::path", "web::data", "web::guard", "web::guarder",
        "web::scope", "web::resource", "web::route", "web::service",
        "web::to", "web::guard", "web::guarder", "web::filter",
        "web::filter_fn", "web::guard", "web::guarder", "web::middleware",
    ],
    # ── clap - argument parser
    "clap": [
        "Command", "Arg", "value_parser", "value_hint", "value_enum",
        "subcommand", "subcommands", "arg", "args", "option", "options",
        "flag", "flags", "group", "groups", "subcommand_required",
        "subcommand_precedence_over_arg", "subcommand_negates_reqs",
        "subcommand_requires_values", "next_display_order", "display_order",
        "help_template", "help_heading", "no_binary_name", "disable_help_flag",
        "disable_help_subcommand", "disable_version_flag", "version",
        "author", "about", "long_about", "before_help", "after_help",
        "before_help_message", "after_help_message", "long_version",
        "term_width", "max_term_width", "use_colored_help", "color",
        "style", "render_help", "render_long_help", "render_version",
        "render_colored_help", "render_colored_long_help", "render_colored_version",
        "ArgAction", "ArgGroup", "ArgValue", "ValueHint", "ValueEnum",
        "Parser", "Subcommand", "Args", "ArgsGroup", "ParserError",
        "clap_builder", "clap_derive", "clap_lex", "clap_complete",
    ],
    # ── sqlx - database library
    "sqlx": [
        "Pool", "MysqlPool", "PgPool", "SqlitePool", "AnyPool",
        "Connection", "MysqlConnection", "PgConnection", "SqliteConnection",
        "AnyConnection", "Acquire", "Executor", "QueryBuilder",
        "query", "query_as", "query_row", "query_row_as", "query_scalar",
        "execute", "fetch", "fetch_one", "fetch_many", "fetch_all",
        "fetch_optional", "try_fetch", "try_fetch_one", "try_fetch_all",
        "transaction", "begin", "commit", "rollback", "is_closed",
        "close", "ping", "batch_execute", "batch_query",
        "PoolOptions", "ConnectionOptions", "TlsMode", "TlsStream",
        "Column", "Database", "Decode", "Encode", "IsNull", "Postgres",
        "Mysql", "Sqlite", "Any", "TypeInfo", "Type", "HasType",
        "SqliteValue", "PgValue", "MysqlValue", "AnyValue",
        "FromRow", "ColumnIndex", "Row", "ValueRef", "ValueType",
        "DatabaseError", "DatabaseErrorKind", "Error", "Result",
        "sqlx::error", "sqlx::query", "sqlx::query_as", "sqlx::query_row",
        "sqlx::query_file", "sqlx::query_file_as", "sqlx::query_file_row",
    ],
    # ── diesel - ORM/query builder
    "diesel": [
        "Connection", "MysqlConnection", "PgConnection", "SqliteConnection",
        "run_query", "load", "get_result", "get_results", "execute",
        "insert_into", "replace_into", "update", "delete", "select",
        "filter", "order", "limit", "offset", "group_by", "having",
        "distinct", "inner_join", "left_join", "right_join", "full_join",
        "join", "join_clause", "JoinOn", "JoinTarget", "Selectable",
        "QueryDsl", "RunQueryDsl", "Expression", "SelectableHelper",
        "AsChangeset", "Identifiable", "QuerySource", "Table",
        "TableAlias", "Column", "Insertable", "SelectableExpression",
        "BoxedQuery", "LimitDsl", "OffsetDsl", "OrderDsl", "GroupByDsl",
        "HavingDsl", "FilterDsl", "SelectDsl", "DistinctDsl",
        "FindDsl", "IntoUpdateTarget", "IntoDeleteTarget",
        "diesel::prelude", "diesel::sql_types", "diesel::expression",
        "diesel::query_builder", "diesel::deserialize",
        "diesel::serialize", "diesel::associations", "diesel::result",
        "diesel::connection", "diesel::migration", "diesel::sql_query",
        "diesel::sql_types", "diesel::expression_methods",
    ],
    # ── tokio-stream - streaming utilities
    "tokio_stream": [
        "StreamExt", "StreamMap", "StreamSet", "iter", "iter_mut",
        "once", "empty", "pending", "poll_fn", "wrapping_inc",
        "wrap_stream", "wrap_future", "wrap_send_stream",
        "Stream", "StreamMapExt", "StreamIter", "FusedStream",
        "stream", "iter", "iter_mut", "once", "empty", "pending",
        "poll_fn", "wrapping_inc", "wrap_stream", "wrap_future",
        "wrap_send_stream", "StreamExt", "StreamMap", "StreamSet",
    ],
    # ── futures - async utilities
    "futures": [
        "future", "stream", "executor", "io", "sink", "channel", "lock",
        "TryFuture", "TryStream", "Future", "Stream", "Executor",
        "Poll", "Ready", "Async", "FutureExt", "StreamExt",
        "try_join", "join", "join_all", "select", "select_ok",
        "try_select", "futures_lite", "futures_util",
        "future::FutureExt", "stream::StreamExt", "io::AsyncRead",
        "io::AsyncWrite", "io::AsyncSeek", "io::AsyncBufRead",
        "lock::Mutex", "lock::MutexGuard", "channel::mpsc",
        "channel::oneshot", "channel::broadcast", "channel::watch",
        "future::ready", "future::lazy", "future::poll_fn",
        "future::poll_immediate", "future::try_join", "future::join",
        "stream::iter", "stream::empty", "stream::once", "stream::pending",
        "stream::poll_fn", "stream::unfold", "stream::repeat",
        "stream::repeat_with", "stream::FusedStream", "stream::FuturesUnordered",
        "stream::FuturesOrdered", "stream::SelectAll", "stream::SelectOk",
    ],
    # ── serde - serialization
    "serde": [
        "Serialize", "Deserialize", "Serializer", "Deserializer",
        "ser", "de", "forward_to_deserialize_any", "serde_derive",
        "SerializeStruct", "SerializeSeq", "SerializeTuple",
        "SerializeTupleStruct", "SerializeTupleVariant", "SerializeMap",
        "SerializeStructVariant", "DeserializeSeed", "IgnoredAny",
        "DeserializeOwned", "SerializeOwned", "de::value",
        "de::SeqAccess", "de::MapAccess", "ser::Error", "de::Error",
        "ser::Impossible", "de::InvalidType", "de::Unexpected",
        "ser::Unexpected", "de::Forward", "ser::CustomType",
        "serde_json", "serde_yaml", "serde_csv", "serde_urlencoded",
    ],
    # ── tracing - logging/tracing
    "tracing": [
        "info", "debug", "warn", "error", "trace", "instrument", "trace_span",
        "debug_span", "info_span", "warn_span", "error_span",
        "Span", "Event", "Metadata", "Level", "Field", "Value",
        "subscriber", "subscriber::Interest", "subscriber::SetGlobalDefault",
        "Layer", "Layered", "Registry", "Collector",
        "FieldSet", "Callsite", "Interest", "Registration",
        "tracing_subscriber", "tracing_core", "tracing_appender",
        "LayerExt", "Subscribe", "with_max_level", "with_max_target",
        "fmt", "fmt::format", "fmt::format::DefaultFields",
        "fmt::format::Format", "fmt::format::Writer",
        "fmt::layer", "fmt::layer::Layer", "fmt::layer::FmtSubscriber",
        "fmt::layer::Layer", "fmt::layer::JsonLayer", "fmt::layer::JsonFields",
    ],
    # ── ureq - HTTP client
    "ureq": [
        "Agent", "AgentBuilder", "Request", "Response", "Builder", "Error",
        "get", "post", "put", "delete", "patch", "head", "options", "trace",
        "build", "call", "send", "send_string", "send_bytes", "send_form",
        "header", "headers", "header_names", "header_values", "status",
        "status_text", "url", "content_length", "content_type",
        "read_to_string", "read_to_vec", "json", "read_json",
        "response", "into_url", "into_response", "try_response",
        "into_string", "into_bytes", "into_json",
        "AgentBuilder", "timeout_connect", "timeout_read", "timeout_write",
        "user_agent", "http_version", "http1_only", "http2_only",
        "tls_config", "tls_client_config", "tls_server_config",
    ],
    # ── reqwest - HTTP client
    "reqwest": [
        "Client", "Request", "Response", "Builder", "Error", "Method",
        "get", "post", "put", "delete", "patch", "head", "options",
        "build", "send", "execute", "send_request", "request",
        "get_url", "url", "method", "headers", "header", "headers_mut",
        "status", "status_code", "version", "reason", "is_success",
        "is_redirection", "is_informational", "is_client_error",
        "is_server_error", "is_error", "text", "json", "bytes", "stream",
        "chunk", "content_length", "content_type", "headers",
        "with", "with_upgrades", "try_send", "try_send_request",
        "into_url", "into_response", "try_response", "into_text",
        "into_json", "into_bytes", "into_stream", "into_chunk",
        "ClientBuilder", "default_headers", "timeout", "connect_timeout",
        "danger_accept_invalid_certs", "danger_accept_invalid_hostnames",
        "tls_built_in_root_certs", "tls_built_in_non_fallback_root_certs",
        "user_agent", "referer", "redirect", "cookie_store",
        "cookie_store_mut", "cookie_jar", "cookie_jar_mut",
        "pool_max_idle_per_host", "pool_idle_timeout", "pool_max_idle_per_host",
        "proxy", "no_proxy", "https_only", "local_address",
        "nodelay", "h3_parse_origin_form", "h3_use_retry_after",
        "h3_max_concurrent_bidi_streams", "h3_max_read_frame_size",
        "h3_initial_stream_window_size", "h3_initial_connection_window_size",
    ],
    # ── tokio - async runtime
    "tokio": [
        "spawn", "task", "spawn_blocking", "spawn_handle", "JoinHandle",
        "JoinSet", "Runtime", "Handle", "Builder", "TaskLocalFuture",
        "task_local", "task_local_key", "task::Id", "task::JoinError",
        "task::JoinSet", "task::LocalSet", "task::Spawn",
        "signal", "sync", "sync::Mutex", "sync::RwLock", "sync::Barrier",
        "sync::Condvar", "sync::Notify", "sync::Semaphore", "sync::watch",
        "sync::mpsc", "sync::broadcast", "sync::oneshot", "sync::MutexGuard",
        "sync::RwLockReadGuard", "sync::RwLockWriteGuard", "sync::OwnedMutexGuard",
        "sync::OwnedRwLockReadGuard", "sync::OwnedRwLockWriteGuard",
        "sync::broadcast::Sender", "sync::broadcast::Receiver",
        "sync::mpsc::Sender", "sync::mpsc::Receiver", "sync::mpsc::Sender",
        "sync::watch::Sender", "sync::watch::Receiver", "sync::oneshot::Sender",
        "sync::oneshot::Receiver", "io", "io::AsyncRead", "io::AsyncWrite",
        "io::AsyncSeek", "io::AsyncBufRead", "io::AsyncReadExt", "io::AsyncWriteExt",
        "io::AsyncSeekExt", "io::BufReader", "io::BufWriter", "io::Lines",
        "io::ReadLines", "io::WriteBytes", "net", "net::TcpListener",
        "net::TcpStream", "net::UnixListener", "net::UnixStream",
        "net::UnixDatagram", "time", "time::Interval", "time::Sleep",
        "time::DelayQueue", "time::timeout", "time::timeout_at",
        "time::Instant", "time::SystemTime", "time::Duration",
        "time::clock", "time::interval", "time::interval_at", "time::sleep",
        "time::sleep_until", "time::timeout", "time::timeout_at",
        "fs", "fs::File", "fs::OpenOptions", "fs::read", "fs::read_to_string",
        "fs::write", "fs::create_dir", "fs::create_dir_all", "fs::remove_dir",
        "fs::remove_dir_all", "fs::remove_file", "fs::rename", "fs::copy",
        "fs::read_dir", "fs::metadata", "fs::set_permissions", "fs::canonicalize",
        "macros", "macros::spawn", "macros::spawn_blocking", "macros::timeout",
        "macros::sleep", "macros::interval", "macros::select",
        "macros::join", "macros::pin", "macros::poll",
    ],
    # ── tokio-util - tokio utilities
    "tokio_util": [
        "codec", "codec::Decoder", "codec::Encoder", "codec::Framed",
        "codec::FramedRead", "codec::FramedWrite", "codec:: length_delimited",
        "codec::length_delimited::LengthDelimitedCodec", "codec::line_length",
        "codec::line_length::LineCodec", "codec::length_delimited::Builder",
        "sync", "sync::poll_semaphore", "sync::PollSemaphore",
        "time", "time::poll_delay", "time::poll_interval", "time::Delay",
        "compat", "compat::Compat", "compat::compat", "compat::compat_with",
        "compat::compat_with_then", "io", "io::poll_read_buf", "io::poll_write_buf",
        "io::AsyncReadExt", "io::AsyncWriteExt", "io::Reader",
        "io::WriteWrapper", "io::read_to_end", "io::write_all",
        "task", "task::spawn_util", "task::AbortHandle", "task::JoinSet",
        "task::task_spawn", "task::task_spawn_with",
        "cancel", "cancel::Cancellation", "cancel::Canceled",
        "cancel::FutureCancel", "cancel::ReadCancel", "cancel::WriteCancel",
    ],
    "std::error": ["Error"],
    "std::fmt": ["Display", "Debug", "Formatter", "write", "write_fmt"],
}
