"""Built-in framework pattern catalog."""

from __future__ import annotations

from ...core.edge import EdgeKind
from ...core.node import NodeKind
from .types import FrameworkPattern, PatternCategory


def built_in_patterns() -> list[FrameworkPattern]:
    """Return the built-in pattern catalog."""
    return [
        # ---- React / JSX ----
        FrameworkPattern(
            id="react_hooks",
            display_name="React Hooks",
            description="Detects React functional components using hooks (useState, useEffect, etc.)",
            framework="react",
            category=PatternCategory.LIFECYCLE,
            min_confidence=0.6,
            required_node_kinds=[NodeKind.FUNCTION, NodeKind.CLASS],
            required_edge_kinds=[EdgeKind.DEFINES, EdgeKind.CALLS],
            signature_names=[
                "useState", "useEffect", "useContext", "useReducer",
                "useMemo", "useCallback", "useRef", "useImperativeHandle",
                "useLayoutEffect", "useDebugValue", "useDeferredValue",
                "useTransition", "useInsertionEffect", "useSyncExternalStore",
            ],
            import_patterns=["react", "@react"],
            min_nodes=2,
            max_nodes=200,
        ),
        FrameworkPattern(
            id="react_class_component",
            display_name="React Class Components",
            description="Detects legacy React class components with lifecycle methods",
            framework="react",
            category=PatternCategory.LIFECYCLE,
            required_node_kinds=[NodeKind.CLASS],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "componentDidMount", "componentDidUpdate",
                "componentWillUnmount", "shouldComponentUpdate",
                "getDerivedStateFromProps", "getSnapshotBeforeUpdate",
            ],
            import_patterns=["react"],
            min_nodes=1,
            max_nodes=50,
        ),
        FrameworkPattern(
            id="react_router",
            display_name="React Router",
            description="Detects React Router route definitions",
            framework="react",
            category=PatternCategory.ROUTING,
            required_node_kinds=[NodeKind.FUNCTION, NodeKind.CLASS],
            required_edge_kinds=[EdgeKind.DEFINES, EdgeKind.CALLS],
            signature_names=[
                "Route", "Routes", "BrowserRouter", "Switch",
                "useNavigate", "useParams", "useLocation", "Link",
            ],
            import_patterns=["react-router"],
            min_nodes=2,
            max_nodes=100,
        ),
        # ---- Express / Node.js ----
        FrameworkPattern(
            id="express_middleware",
            display_name="Express Middleware",
            description="Detects Express middleware functions and app.use() calls",
            framework="express",
            category=PatternCategory.MIDDLEWARE,
            required_node_kinds=[NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES, EdgeKind.CALLS],
            signature_names=["app.use", "router.use", "next"],
            import_patterns=["express"],
            min_nodes=2,
            max_nodes=200,
        ),
        FrameworkPattern(
            id="express_routes",
            display_name="Express Routes",
            description="Detects Express route handlers",
            framework="express",
            category=PatternCategory.ROUTING,
            required_node_kinds=[NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES, EdgeKind.CALLS],
            signature_names=[
                "app.get", "app.post", "app.put", "app.delete",
                "app.patch", "router.get", "router.post",
            ],
            import_patterns=["express"],
            min_nodes=2,
            max_nodes=200,
        ),
        # ---- Spring / Java ----
        FrameworkPattern(
            id="spring_di",
            display_name="Spring Dependency Injection",
            description="Detects Spring DI annotations: @Autowired, @Inject, @Component, @Bean",
            framework="spring",
            category=PatternCategory.DEPENDENCY_INJECTION,
            required_node_kinds=[NodeKind.CLASS, NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "Autowired", "Inject", "Component", "Service",
                "Repository", "Controller", "RestController", "Bean",
                "Configuration", "Qualifier", "Primary",
            ],
            import_patterns=["org.springframework", "javax.inject"],
            min_nodes=2,
            max_nodes=500,
        ),
        FrameworkPattern(
            id="spring_rest",
            display_name="Spring REST Controllers",
            description="Detects Spring REST endpoint mappings",
            framework="spring",
            category=PatternCategory.ROUTING,
            required_node_kinds=[NodeKind.CLASS, NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "GetMapping", "PostMapping", "PutMapping",
                "DeleteMapping", "PatchMapping", "RequestMapping",
                "ResponseBody", "RequestBody",
            ],
            import_patterns=["org.springframework"],
            min_nodes=2,
            max_nodes=200,
        ),
        FrameworkPattern(
            id="spring_jpa",
            display_name="Spring Data JPA",
            description="Detects JPA entity classes and repository interfaces",
            framework="spring",
            category=PatternCategory.DATA_MAPPING,
            required_node_kinds=[NodeKind.CLASS],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "Entity", "Table", "Id", "GeneratedValue",
                "OneToMany", "ManyToOne", "ManyToMany", "OneToOne",
                "Column", "Transient", "Repository",
                "CrudRepository", "JpaRepository",
            ],
            import_patterns=["javax.persistence", "jakarta.persistence"],
            min_nodes=2,
            max_nodes=300,
        ),
        # ---- Django / Python ----
        FrameworkPattern(
            id="django_middleware",
            display_name="Django Middleware",
            description="Detects Django middleware classes",
            framework="django",
            category=PatternCategory.MIDDLEWARE,
            required_node_kinds=[NodeKind.CLASS, NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "process_request", "process_response", "process_view",
                "process_exception", "process_template_response",
            ],
            import_patterns=["django"],
            min_nodes=2,
            max_nodes=100,
        ),
        FrameworkPattern(
            id="django_models",
            display_name="Django Models",
            description="Detects Django ORM model classes",
            framework="django",
            category=PatternCategory.DATA_MAPPING,
            required_node_kinds=[NodeKind.CLASS],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "Model", "CharField", "IntegerField", "ForeignKey",
                "ManyToManyField", "TextField", "DateField",
                "DateTimeField", "BooleanField", "EmailField",
                "URLField", "OneToOneField",
            ],
            import_patterns=["django.db"],
            min_nodes=2,
            max_nodes=300,
        ),
        FrameworkPattern(
            id="django_views",
            display_name="Django Views",
            description="Detects Django view functions and class-based views",
            framework="django",
            category=PatternCategory.ROUTING,
            required_node_kinds=[NodeKind.FUNCTION, NodeKind.CLASS],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "View", "TemplateView", "ListView", "DetailView",
                "CreateView", "UpdateView", "DeleteView", "FormView",
            ],
            import_patterns=["django.views"],
            min_nodes=1,
            max_nodes=200,
        ),
        # ---- FastAPI / Python ----
        FrameworkPattern(
            id="fastapi_routes",
            display_name="FastAPI Routes",
            description="Detects FastAPI route decorators and dependency injection",
            framework="fastapi",
            category=PatternCategory.ROUTING,
            required_node_kinds=[NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "APIRouter", "Depends", "Body", "Query",
                "Path", "Header",
            ],
            import_patterns=["fastapi", "starlette"],
            min_nodes=2,
            max_nodes=200,
        ),
        # ---- Angular / TypeScript ----
        FrameworkPattern(
            id="angular_components",
            display_name="Angular Components",
            description="Detects Angular component decorators and module definitions",
            framework="angular",
            category=PatternCategory.GENERIC,
            required_node_kinds=[NodeKind.CLASS, NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "Component", "Module", "Directive", "Pipe",
                "Injectable", "Input", "Output", "ViewChild",
                "HostListener", "OnInit", "OnDestroy", "ngOnInit",
                "ngOnDestroy", "NgModule",
            ],
            import_patterns=["@angular/core", "@angular"],
            min_nodes=2,
            max_nodes=500,
        ),
        # ---- NestJS / TypeScript ----
        FrameworkPattern(
            id="nestjs_controllers",
            display_name="NestJS Controllers",
            description="Detects NestJS controller decorators and route handlers",
            framework="nestjs",
            category=PatternCategory.ROUTING,
            required_node_kinds=[NodeKind.CLASS, NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "Controller", "Get", "Post", "Put", "Delete",
                "Patch", "Body", "Param", "Query", "Inject",
                "Injectable", "Module", "UseGuards",
                "UseInterceptors", "HttpException",
            ],
            import_patterns=["@nestjs"],
            min_nodes=2,
            max_nodes=500,
        ),
        # ---- Vue / Composition API ----
        FrameworkPattern(
            id="vue_composition",
            display_name="Vue Composition API",
            description="Detects Vue 3 Composition API usage (ref, reactive, computed, etc.)",
            framework="vue",
            category=PatternCategory.STATE_MANAGEMENT,
            required_node_kinds=[NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES, EdgeKind.CALLS],
            signature_names=[
                "ref", "reactive", "computed", "watch",
                "watchEffect", "onMounted", "onUnmounted",
                "onBeforeMount", "onBeforeUnmount",
                "provide", "inject", "defineComponent",
            ],
            import_patterns=["vue"],
            min_nodes=2,
            max_nodes=200,
        ),
        # ---- Flask / Python ----
        FrameworkPattern(
            id="flask_routes",
            display_name="Flask Routes",
            description="Detects Flask route decorators and application factory pattern",
            framework="flask",
            category=PatternCategory.ROUTING,
            required_node_kinds=[NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "Blueprint", "before_request", "after_request",
                "teardown_request", "errorhandler", "url_for",
                "render_template", "jsonify",
            ],
            import_patterns=["flask"],
            min_nodes=2,
            max_nodes=200,
        ),
        # ---- Testing frameworks ----
        FrameworkPattern(
            id="jest_tests",
            display_name="Jest Test Suite",
            description="Detects Jest test patterns (describe, it, test, beforeEach, etc.)",
            framework="jest",
            category=PatternCategory.TESTING,
            required_node_kinds=[NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "describe", "it", "test", "beforeEach", "afterEach",
                "beforeAll", "afterAll", "expect", "jest.fn",
                "jest.mock", "jest.spyOn",
            ],
            import_patterns=["jest"],
            min_nodes=3,
            max_nodes=500,
        ),
        FrameworkPattern(
            id="pytest_tests",
            display_name="Pytest Test Suite",
            description="Detects pytest test functions, fixtures, and parametrize patterns",
            framework="pytest",
            category=PatternCategory.TESTING,
            required_node_kinds=[NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "fixture", "parametrize", "pytestmark", "conftest",
                "tmp_path", "monkeypatch", "caplog", "capfd",
            ],
            import_patterns=["pytest"],
            min_nodes=3,
            max_nodes=500,
        ),
        FrameworkPattern(
            id="junit_tests",
            display_name="JUnit Test Suite",
            description="Detects JUnit test annotations (@Test, @BeforeEach, @ParameterizedTest, etc.)",
            framework="junit",
            category=PatternCategory.TESTING,
            required_node_kinds=[NodeKind.CLASS, NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "Test", "BeforeEach", "AfterEach", "BeforeAll", "AfterAll",
                "ParameterizedTest", "Disabled", "TempDir", "RepeatedTest",
                "Nested", "DisplayName", "ExtendWith", "RegisterExtension",
            ],
            import_patterns=["org.junit", "junit.jupiter"],
            min_nodes=3,
            max_nodes=500,
        ),
        # ---- GraphQL ----
        FrameworkPattern(
            id="graphql_schema",
            display_name="GraphQL Schema",
            description="Detects GraphQL type definitions and resolvers",
            framework="graphql",
            category=PatternCategory.DATA_MAPPING,
            required_node_kinds=[NodeKind.CLASS, NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "GraphQLSchema", "GraphQLObjectType", "GraphQLField",
                "GraphQLScalarType", "GraphQLInterfaceType",
                "GraphQLUnionType", "GraphQLInputObjectType",
                "GraphQLList", "GraphQLNonNull",
                "makeExecutableSchema", "createSchema",
            ],
            import_patterns=["graphql", "apollo", "type-graphql"],
            min_nodes=2,
            max_nodes=500,
        ),
        # ---- CLI frameworks ----
        FrameworkPattern(
            id="click_cli",
            display_name="Click CLI",
            description="Detects Click CLI commands and groups",
            framework="click",
            category=PatternCategory.COMMAND_LINE,
            required_node_kinds=[NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "click.command", "click.group", "click.option",
                "click.argument", "click.pass_context",
            ],
            import_patterns=["click"],
            min_nodes=1,
            max_nodes=100,
        ),
        FrameworkPattern(
            id="argparse_cli",
            display_name="Argparse CLI",
            description="Detects argparse CLI argument definitions",
            framework="argparse",
            category=PatternCategory.COMMAND_LINE,
            required_node_kinds=[NodeKind.FUNCTION, NodeKind.CLASS],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "ArgumentParser", "add_argument", "add_subparsers",
                "parse_args", "parse_known_args",
            ],
            import_patterns=["argparse"],
            min_nodes=1,
            max_nodes=100,
        ),
        # ---- ORM frameworks ----
        FrameworkPattern(
            id="sqlalchemy_models",
            display_name="SQLAlchemy Models",
            description="Detects SQLAlchemy declarative model classes",
            framework="sqlalchemy",
            category=PatternCategory.DATA_MAPPING,
            required_node_kinds=[NodeKind.CLASS],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "Column", "Integer", "String", "Text", "Boolean",
                "ForeignKey", "relationship", "declarative_base",
                "Mapped", "mapped_column",
            ],
            import_patterns=["sqlalchemy"],
            min_nodes=1,
            max_nodes=300,
        ),
        FrameworkPattern(
            id="pydantic_models",
            display_name="Pydantic Models",
            description="Detects Pydantic data model classes and validators",
            framework="pydantic",
            category=PatternCategory.VALIDATION,
            required_node_kinds=[NodeKind.CLASS],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "BaseModel", "Field", "validator", "field_validator",
                "model_validator", "root_validator", "PrivateAttr",
            ],
            import_patterns=["pydantic"],
            min_nodes=1,
            max_nodes=200,
        ),
        # ---- State management ----
        FrameworkPattern(
            id="redux_state",
            display_name="Redux State Management",
            description="Detects Redux store, reducers, and action creators",
            framework="redux",
            category=PatternCategory.STATE_MANAGEMENT,
            required_node_kinds=[NodeKind.FUNCTION, NodeKind.CLASS],
            required_edge_kinds=[EdgeKind.DEFINES, EdgeKind.CALLS],
            signature_names=[
                "createStore", "combineReducers", "dispatch",
                "useSelector", "useDispatch", "applyMiddleware",
                "createSlice", "createAsyncThunk",
            ],
            import_patterns=["redux", "@reduxjs/toolkit"],
            min_nodes=2,
            max_nodes=300,
        ),
        FrameworkPattern(
            id="mobx_state",
            display_name="MobX State Management",
            description="Detects MobX observable state and reactions",
            framework="mobx",
            category=PatternCategory.STATE_MANAGEMENT,
            required_node_kinds=[NodeKind.CLASS, NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "observable", "computed", "action", "runInAction",
                "autorun", "when", "reaction", "observe",
            ],
            import_patterns=["mobx"],
            min_nodes=2,
            max_nodes=200,
        ),
        # ---- Middleware patterns ----
        FrameworkPattern(
            id="cors_middleware",
            display_name="CORS Middleware",
            description="Detects CORS configuration middleware",
            framework="generic",
            category=PatternCategory.MIDDLEWARE,
            required_node_kinds=[NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "cors", "CORS", "Access-Control", "allow_origin",
                "allow_methods", "allow_headers",
            ],
            import_patterns=["cors", "flask-cors", "django-cors-headers"],
            min_nodes=1,
            max_nodes=50,
        ),
        FrameworkPattern(
            id="auth_middleware",
            display_name="Authentication Middleware",
            description="Detects authentication middleware and decorators",
            framework="generic",
            category=PatternCategory.MIDDLEWARE,
            required_node_kinds=[NodeKind.FUNCTION, NodeKind.CLASS],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "authenticate", "login_required", "permission_required",
                "jwt_required", "oauth", "auth_guard", "middleware",
            ],
            import_patterns=["auth", "jwt", "oauth", "passport"],
            min_nodes=1,
            max_nodes=100,
        ),
        # ---- Data validation ----
        FrameworkPattern(
            id="marshmallow_validation",
            display_name="Marshmallow Schemas",
            description="Detects Marshmallow schema definitions",
            framework="marshmallow",
            category=PatternCategory.VALIDATION,
            required_node_kinds=[NodeKind.CLASS],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "Schema", "fields", "load_only", "dump_only",
                "post_load", "pre_load", "validates",
            ],
            import_patterns=["marshmallow"],
            min_nodes=1,
            max_nodes=200,
        ),
        # ---- Event-driven ----
        FrameworkPattern(
            id="event_emitter",
            display_name="Event Emitter Pattern",
            description="Detects event emitter/listener patterns",
            framework="generic",
            category=PatternCategory.GENERIC,
            required_node_kinds=[NodeKind.FUNCTION, NodeKind.CLASS],
            required_edge_kinds=[EdgeKind.DEFINES, EdgeKind.CALLS],
            signature_names=[
                "emit", "on", "off", "once", "addListener",
                "removeListener", "eventemitter", "EventEmitter",
                "signal", "subscribe", "unsubscribe",
            ],
            import_patterns=["events", "eventemitter3"],
            min_nodes=2,
            max_nodes=200,
        ),
        # ---- Async patterns ----
        FrameworkPattern(
            id="asyncio_patterns",
            display_name="Asyncio Patterns",
            description="Detects asyncio task, coroutine, and event loop patterns",
            framework="asyncio",
            category=PatternCategory.LIFECYCLE,
            required_node_kinds=[NodeKind.FUNCTION, NodeKind.CLASS],
            required_edge_kinds=[EdgeKind.DEFINES, EdgeKind.CALLS],
            signature_names=[
                "asyncio.run", "asyncio.create_task", "asyncio.gather",
                "asyncio.wait", "asyncio.sleep", "asyncio.Event",
                "asyncio.Lock", "asyncio.Queue", "asyncio.Semaphore",
                "asyncio.TaskGroup",
            ],
            import_patterns=["asyncio"],
            min_nodes=2,
            max_nodes=200,
        ),
        # ---- Logging ----
        FrameworkPattern(
            id="structured_logging",
            display_name="Structured Logging",
            description="Detects structured logging patterns (JSON, loguru, structlog)",
            framework="generic",
            category=PatternCategory.GENERIC,
            required_node_kinds=[NodeKind.FUNCTION, NodeKind.CLASS],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "logging.getLogger", "structlog", "loguru",
                "logger.info", "logger.error", "logger.warning",
                "logger.debug", "bind", "process",
            ],
            import_patterns=["logging", "structlog", "loguru"],
            min_nodes=1,
            max_nodes=100,
        ),
    ]
