"""Built-in framework pattern catalog."""

from __future__ import annotations

from ...core.edge import EdgeKind
from ...core.node import NodeKind
from .types import FrameworkPattern, PatternCategory


def _builtin_patterns() -> list[FrameworkPattern]:
    """Return the built-in pattern catalog."""
    return [
        # ---- React / JSX ----
        FrameworkPattern(
            id="react_hooks",
            display_name="React Hooks",
            description="Detects React functional components using hooks (useState, useEffect, etc.)",
            framework="react",
            category=PatternCategory.LIFECYCLE,
            min_confidence=0.6,
            required_node_kinds=[NodeKind.FUNCTION, NodeKind.CLASS],
            required_edge_kinds=[EdgeKind.DEFINES, EdgeKind.CALLS],
            signature_names=[
                "useState", "useEffect", "useContext", "useReducer",
                "useMemo", "useCallback", "useRef", "useImperativeHandle",
                "useLayoutEffect", "useDebugValue", "useDeferredValue",
                "useTransition", "useInsertionEffect", "useSyncExternalStore",
            ],
            import_patterns=["react", "@react"],
            min_nodes=2,
            max_nodes=200,
        ),
        FrameworkPattern(
            id="react_class_component",
            display_name="React Class Components",
            description="Detects legacy React class components with lifecycle methods",
            framework="react",
            category=PatternCategory.LIFECYCLE,
            required_node_kinds=[NodeKind.CLASS],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "componentDidMount", "componentDidUpdate",
                "componentWillUnmount", "shouldComponentUpdate",
                "getDerivedStateFromProps", "getSnapshotBeforeUpdate",
            ],
            import_patterns=["react"],
            min_nodes=1,
            max_nodes=50,
        ),
        FrameworkPattern(
            id="react_router",
            display_name="React Router",
            description="Detects React Router route definitions",
            framework="react",
            category=PatternCategory.ROUTING,
            required_node_kinds=[NodeKind.FUNCTION, NodeKind.CLASS],
            required_edge_kinds=[EdgeKind.DEFINES, EdgeKind.CALLS],
            signature_names=[
                "Route", "Routes", "BrowserRouter", "Switch",
                "useNavigate", "useParams", "useLocation", "Link",
            ],
            import_patterns=["react-router"],
            min_nodes=2,
            max_nodes=100,
        ),
        # ---- Express / Node.js ----
        FrameworkPattern(
            id="express_middleware",
            display_name="Express Middleware",
            description="Detects Express middleware functions and app.use() calls",
            framework="express",
            category=PatternCategory.MIDDLEWARE,
            required_node_kinds=[NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES, EdgeKind.CALLS],
            signature_names=["app.use", "router.use", "next"],
            import_patterns=["express"],
            min_nodes=2,
            max_nodes=200,
        ),
        FrameworkPattern(
            id="express_routes",
            display_name="Express Routes",
            description="Detects Express route handlers",
            framework="express",
            category=PatternCategory.ROUTING,
            required_node_kinds=[NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES, EdgeKind.CALLS],
            signature_names=[
                "app.get", "app.post", "app.put", "app.delete",
                "app.patch", "router.get", "router.post",
            ],
            import_patterns=["express"],
            min_nodes=2,
            max_nodes=200,
        ),
        # ---- Spring / Java ----
        FrameworkPattern(
            id="spring_di",
            display_name="Spring Dependency Injection",
            description="Detects Spring DI annotations: @Autowired, @Inject, @Component, @Bean",
            framework="spring",
            category=PatternCategory.DEPENDENCY_INJECTION,
            required_node_kinds=[NodeKind.CLASS, NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "Autowired", "Inject", "Component", "Service",
                "Repository", "Controller", "RestController", "Bean",
                "Configuration", "Qualifier", "Primary",
            ],
            import_patterns=["org.springframework", "javax.inject"],
            min_nodes=2,
            max_nodes=500,
        ),
        FrameworkPattern(
            id="spring_rest",
            display_name="Spring REST Controllers",
            description="Detects Spring REST endpoint mappings",
            framework="spring",
            category=PatternCategory.ROUTING,
            required_node_kinds=[NodeKind.CLASS, NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "GetMapping", "PostMapping", "PutMapping",
                "DeleteMapping", "PatchMapping", "RequestMapping",
                "ResponseBody", "RequestBody",
            ],
            import_patterns=["org.springframework"],
            min_nodes=2,
            max_nodes=200,
        ),
        FrameworkPattern(
            id="spring_jpa",
            display_name="Spring Data JPA",
            description="Detects JPA entity classes and repository interfaces",
            framework="spring",
            category=PatternCategory.DATA_MAPPING,
            required_node_kinds=[NodeKind.CLASS],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "Entity", "Table", "Id", "GeneratedValue",
                "OneToMany", "ManyToOne", "ManyToMany", "OneToOne",
                "Column", "Transient", "Repository",
                "CrudRepository", "JpaRepository",
            ],
            import_patterns=["javax.persistence", "jakarta.persistence"],
            min_nodes=2,
            max_nodes=300,
        ),
        # ---- Django / Python ----
        FrameworkPattern(
            id="django_middleware",
            display_name="Django Middleware",
            description="Detects Django middleware classes",
            framework="django",
            category=PatternCategory.MIDDLEWARE,
            required_node_kinds=[NodeKind.CLASS, NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "process_request", "process_response", "process_view",
                "process_exception", "process_template_response",
            ],
            import_patterns=["django"],
            min_nodes=2,
            max_nodes=100,
        ),
        FrameworkPattern(
            id="django_models",
            display_name="Django Models",
            description="Detects Django ORM model classes",
            framework="django",
            category=PatternCategory.DATA_MAPPING,
            required_node_kinds=[NodeKind.CLASS],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "Model", "CharField", "IntegerField", "ForeignKey",
                "ManyToManyField", "TextField", "DateField",
                "DateTimeField", "BooleanField", "EmailField",
                "URLField", "OneToOneField",
            ],
            import_patterns=["django.db"],
            min_nodes=2,
            max_nodes=300,
        ),
        FrameworkPattern(
            id="django_views",
            display_name="Django Views",
            description="Detects Django view functions and class-based views",
            framework="django",
            category=PatternCategory.ROUTING,
            required_node_kinds=[NodeKind.FUNCTION, NodeKind.CLASS],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "View", "TemplateView", "ListView", "DetailView",
                "CreateView", "UpdateView", "DeleteView", "FormView",
            ],
            import_patterns=["django.views"],
            min_nodes=1,
            max_nodes=200,
        ),
        # ---- FastAPI / Python ----
        FrameworkPattern(
            id="fastapi_routes",
            display_name="FastAPI Routes",
            description="Detects FastAPI route decorators and dependency injection",
            framework="fastapi",
            category=PatternCategory.ROUTING,
            required_node_kinds=[NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "APIRouter", "Depends", "Body", "Query",
                "Path", "Header",
            ],
            import_patterns=["fastapi", "starlette"],
            min_nodes=2,
            max_nodes=200,
        ),
        # ---- Angular / TypeScript ----
        FrameworkPattern(
            id="angular_components",
            display_name="Angular Components",
            description="Detects Angular component decorators and module definitions",
            framework="angular",
            category=PatternCategory.GENERIC,
            required_node_kinds=[NodeKind.CLASS, NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "Component", "Module", "Directive", "Pipe",
                "Injectable", "Input", "Output", "ViewChild",
                "HostListener", "OnInit", "OnDestroy", "ngOnInit",
                "ngOnDestroy", "NgModule",
            ],
            import_patterns=["@angular/core", "@angular"],
            min_nodes=2,
            max_nodes=500,
        ),
        # ---- NestJS / TypeScript ----
        FrameworkPattern(
            id="nestjs_controllers",
            display_name="NestJS Controllers",
            description="Detects NestJS controller decorators and route handlers",
            framework="nestjs",
            category=PatternCategory.ROUTING,
            required_node_kinds=[NodeKind.CLASS, NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES],
            signature_names=[
                "Controller", "Get", "Post", "Put", "Delete",
                "Patch", "Body", "Param", "Query", "Inject",
                "Injectable", "Module", "UseGuards",
                "UseInterceptors", "HttpException",
            ],
            import_patterns=["@nestjs"],
            min_nodes=2,
            max_nodes=500,
        ),
        # ---- Vue / Composition API ----
        FrameworkPattern(
            id="vue_composition",
            display_name="Vue Composition API",
            description="Detects Vue 3 Composition API usage (ref, reactive, computed, etc.)",
            framework="vue",
            category=PatternCategory.STATE_MANAGEMENT,
            required_node_kinds=[NodeKind.FUNCTION],
            required_edge_kinds=[EdgeKind.DEFINES, EdgeKind.CALLS],
            signature_names=[
                "ref", "reactive", "computed", "watch",
                "watchEffect", "onMounted", "onUnmounted",
                "onBeforeMount", "onBeforeUnmount",
                "provide", "inject", "defineComponent",
            ],
            import_patterns=["vue"],
            min_nodes=2,
            max_nodes=200,
        ),
    ]
